import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
const stage='../evidence/production/architecture-detail-v1',read=async p=>JSON.parse(await fs.readFile(p,'utf8'));
async function getRun(log,type){const lines=(await fs.readFile(`${stage}/${log}`,'utf8')).trim().split('\n').map(JSON.parse),e=lines.find(e=>e.type==='completed');assert(e?.data?.runPath);return {id:e.data.run.runId,path:e.data.runPath,data:await read(path.join(e.data.runPath,type+'.json'))};}
const candidate=await getRun('capture.jsonl','traversal'),startup=await getRun('startup.jsonl','startup');
const baseline=await read('assets/generated/.game-dev/runs/run_1789053170347_b49660160e8a4c55a2b1ac622f0fe2d4/traversal.json');
for(const field of ['quality','viewport','dpr','browser','graphics','profile'])assert.deepEqual(candidate.data[field],baseline[field]);
for(const role of ['baseline','candidate','startup'])assert((await read(`${stage}/${role}-verify.json`)).ok);
const goal=await read('.game-dev/goals/balanced-architecture-detail.json');assert.equal(goal.state.status,'met');assert.equal(goal.state.iterations.length,1);assert.equal(goal.state.iterations[0].runId,candidate.id);
assert.equal(candidate.data.buildId,startup.data.buildId);
for(const f of candidate.data.inputs){const b=await fs.readFile(f.path);assert.equal(b.length,f.bytes);assert.equal(createHash('sha256').update(b).digest('hex'),f.sha256);}
for(const phase of ['initial','final'])assert.equal(candidate.data[phase].world.architecture.detail.active,'balanced');
assert.equal(startup.data.ready.state.world.architecture.detail.active,'balanced');assert(startup.data.firstPlayTransferredBytes<=8_000_000);assert(startup.data.ready.observation.readyAt<=6000);
const visual=await read(`${stage}/views/comparison.json`);assert.equal(visual.length,10);assert(visual.filter(r=>r.quality==='high').every(r=>r.identical));
const browser=await read(`${stage}/browser.json`),journey=await read(`${stage}/journey/report.json`),context=await read(`${stage}/context/report.json`);assert(browser.pass&&browser.rows.length===7&&journey.pass&&context.pass);
const unit=await fs.readFile(`${stage}/unit.log`,'utf8');assert(unit.includes('pass 76')&&unit.includes('fail 0'));
const geometry=await read(`${stage}/geometry.json`);const asset=await fs.readFile('public/assets/headquarters/streamed/'+geometry.asset);assert.equal(createHash('sha256').update(asset).digest('hex'),geometry.sha256);
const result={date:new Date().toISOString(),pass:true,buildId:candidate.data.buildId,goalStatus:goal.state.status,baseline:{runId:goal.baseline.runId,triangles:baseline.summary.maxActiveTriangles},candidate:{runId:candidate.id,...candidate.data.summary},startup:{runId:startup.id,bytes:startup.data.firstPlayTransferredBytes,readyMs:startup.data.ready.observation.readyAt,profile:startup.data.profile},geometry:{before:geometry.before,balanced:geometry.after,optionalBytes:geometry.bytes},checks:{unit:76,journey:37,browserCases:7,highPixelIdenticalViews:5,balancedComparedViews:5,balancedContextRestored:true,internalBrowser:'Task studio inspected; High/Balanced switched; saved Balanced/mute retained, paused.'},visual,fullReleaseAccepted:false,limits:['One comparable 90-second traversal and one synthetic startup; not a repeat study or real-device/hosted test.','High geometry and five fixed views unchanged; Balanced topology is lossy and inspected only within stated views.','Draw budgets remain open: this change reduces submitted triangles, not draw calls.','Native GPU time/VRAM, broad art/camera/audio/accessibility/device/human review and remaining release gates are unverified.']};
await fs.writeFile(`${stage}/assessment.json`,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({pass:true,buildId:result.buildId,triangles:result.candidate.maxActiveTriangles,startup:result.startup}));
