import fs from 'node:fs/promises';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
const file='public/diagnostic-scene.glb';
const bytes=await fs.readFile(file);
assert.equal(bytes.toString('utf8',0,4),'glTF');
assert.equal(bytes.readUInt32LE(4),2);
assert.equal(bytes.readUInt32LE(8),bytes.length);
assert.equal(bytes.toString('utf8',16,20),'JSON');
const doc=JSON.parse(bytes.toString('utf8',20,20+bytes.readUInt32LE(12)));
const triangles=doc.meshes.reduce((n,m)=>n+m.primitives.reduce((s,p)=>s+(p.indices!==undefined?doc.accessors[p.indices].count:doc.accessors[p.attributes.POSITION].count)/3,0),0);
assert(bytes.length<10*1024*1024);
assert(triangles<100000);
assert(doc.meshes.length>10);
assert(doc.materials.every(m=>m.pbrMetallicRoughness));
assert(doc.images.some(i=>i.bufferView!==undefined&&!i.uri));
assert(doc.skins.length>=1);
assert(doc.animations.length>=1);
assert(doc.animations.some(a=>a.channels.some(c=>c.target.path==='rotation')));
const report={pass:true,file,bytes:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex'),meshes:doc.meshes.length,triangles,materials:doc.materials.length,embeddedImages:doc.images.filter(i=>i.bufferView!==undefined).length,skins:doc.skins.length,joints:doc.skins.map(s=>s.joints.length),animations:doc.animations.map(a=>({name:a.name,channels:a.channels.length})),extensions:doc.extensionsUsed??[]};
await fs.writeFile('evidence/glb-structure.json',JSON.stringify(report,null,2));
console.log(JSON.stringify(report,null,2));
