import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const evidence=path.join(root,'evidence');
await fs.mkdir(evidence,{recursive:true});
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
const consoleErrors=[],failedRequests=[],remoteRequests=[],checks=[];
page.on('pageerror',e=>consoleErrors.push(e.message));
page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))consoleErrors.push(m.text())});
page.on('requestfailed',r=>failedRequests.push({url:r.url(),error:r.failure()}));
page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:43197')&&!r.url().startsWith('data:')&&!r.url().startsWith('blob:'))remoteRequests.push(r.url())});
const state=()=>page.evaluate(()=>window.__smoke.getState());
const check=(name,fn)=>{fn();checks.push({name,pass:true});};
try{
 await page.goto('http://127.0.0.1:43197/',{waitUntil:'networkidle'});
 await page.waitForFunction(()=>window.__smoke?.getState().ready,{timeout:45000});
 const initial=await state();
 check('Imported actual GLB meshes, textures, skin and animation',()=>{assert(initial.meshes>10);assert(initial.textures>=1);assert(initial.textureReady);assert(initial.skeletons>=1);assert(initial.animationGroups.length>=1)});
 await page.waitForTimeout(380);
 const moved=await state();
 check('Imported skeletal animation changes bone transforms',()=>assert.notDeepEqual(initial.bonePose,moved.bonePose));
 await page.getByRole('button',{name:'Pause animation'}).click();
 await page.waitForTimeout(100);
 const pausedA=await state();await page.waitForTimeout(300);const pausedB=await state();
 check('Pause stops imported animation',()=>{assert(pausedB.paused);assert.deepEqual(pausedA.bonePose,pausedB.bonePose)});
 await page.screenshot({path:path.join(evidence,'browser-desktop.png')});
 await page.getByRole('button',{name:'Evening lighting'}).click();
 assert((await state()).evening);
 await page.waitForTimeout(200);await page.screenshot({path:path.join(evidence,'browser-evening.png')});
 const dayImage=await fs.readFile(path.join(evidence,'browser-desktop.png'));
 const eveningImage=await fs.readFile(path.join(evidence,'browser-evening.png'));
 check('Lighting control changes rendered pixels',()=>assert(!dayImage.equals(eveningImage)));
 const beforeOrbit=await state();
 await page.mouse.move(720,430);await page.mouse.down();await page.mouse.move(900,470,{steps:15});await page.mouse.up();
 await page.waitForTimeout(250);const afterOrbit=await state();
 check('Pointer drag orbits the camera',()=>assert(Math.abs(afterOrbit.camera.alpha-beforeOrbit.camera.alpha)>.1));
 await page.getByRole('button',{name:'Reset',exact:true}).click();
 const reset=await state();
 check('Reset restores camera, lighting and playing animation',()=>{assert(!reset.paused&&!reset.evening);assert(Math.abs(reset.camera.alpha-(Math.PI/2-.5))<.001);assert(Math.abs(reset.camera.radius-7)<.001)});
 await page.keyboard.press('p');assert((await state()).paused);await page.keyboard.press('r');assert(!(await state()).paused);checks.push({name:'P and R keyboard shortcuts',pass:true});
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(350);
 const portrait=await state();
 check('Portrait canvas resizes',()=>{assert.equal(portrait.renderSize.width,390);assert.equal(portrait.renderSize.height,844)});
 await page.getByRole('button',{name:'Pause animation'}).click();
 await page.screenshot({path:path.join(evidence,'browser-portrait.png')});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
 check('Portrait has no horizontal overflow',()=>assert(!overflow));
 await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>window.__smoke?.getState().ready);
 const final=await state();check('Clean reload restores a working asset',()=>assert(final.ready&&!final.paused&&!final.evening));
 await page.setViewportSize({width:1440,height:900});await page.waitForTimeout(2500);
 const telemetry=await state();
 check('No JavaScript errors or failed asset requests',()=>{assert.deepEqual(consoleErrors,[]);assert.deepEqual(failedRequests,[]);assert.deepEqual(telemetry.errors,[])});
 check('No external runtime dependencies',()=>assert.deepEqual(remoteRequests,[]));
 const sorted=telemetry.frameMs.slice().sort((a,b)=>a-b);
 const report={pass:true,checkedAt:new Date().toISOString(),browserVersion:browser.version(),checks,consoleErrors,failedRequests,remoteRequests,scene:telemetry,browserObservedFrameMs:{median:sorted[Math.floor(sorted.length/2)],p95:sorted[Math.floor(sorted.length*.95)],samples:sorted.length},limitation:'A diagnostic headless Chrome run; timing is not a representative finished-game benchmark or independent hardware-performance evidence.'};
 await fs.writeFile(path.join(evidence,'browser-test.json'),JSON.stringify(report,null,2));
 console.log(JSON.stringify({pass:true,checks,scene:{meshes:telemetry.meshes,textures:telemetry.textures,skeletons:telemetry.skeletons,animations:telemetry.animationGroups.length},timing:report.browserObservedFrameMs},null,2));
}catch(error){await page.screenshot({path:path.join(evidence,'browser-failure.png')});await fs.writeFile(path.join(evidence,'browser-failure.json'),JSON.stringify({error:error.stack,checks,consoleErrors,failedRequests,state:await state().catch(()=>null)},null,2));throw error;}finally{await browser.close();}
