export const ATLAS_DATE='2026-09-10';
export const atlasCategories=['Workspace','Models','Context','Tools','Delivery','Developer'];
export const atlasSurfaces=['Desktop','CLI','IDE','Web','Cloud','Mobile'];
const local=['Desktop','CLI','IDE'],everyday=['Desktop','Web'];
const entry=(id,title,category,summary,example,surfaces,source,prerequisites,mission)=>({id,title,category,summary,example,surfaces,source:'https://learn.chatgpt.com/docs/'+source,prerequisites,mission,verifiedAt:ATLAS_DATE,claim:'official',evidence:'Current official documentation; the example is a suggested practice request.'});

export const atlas=[
 entry('projects','Projects and local folders','Workspace','Keep related outcomes and sources together. A local project points to a working folder; a ChatGPT project has its own project sources and instructions.','Identify the project folder and the current source brief before updating this onboarding workflow.',[...everyday,'CLI','IDE'],'projects','Choose the intended project or directory; project types have different context behavior.',4),
 entry('focused-tasks','One task, one outcome','Workspace','Separate distinct deliverables into focused tasks. Keep related work in a project so the sources remain easy to find.','Create a separate review task for the onboarding checklist. Give it the client brief and a concrete verification requirement.',everyday,'projects','New-task controls and source access depend on the selected client and project.',4),
 entry('pinning','Pinning and archiving','Workspace','Pinning makes work easier to find. It does not supply context, grant access, or increase reasoning effort. Archived tasks can be restored.','Pin the onboarding review so I can return to it. Archive the completed draft when I ask you to tidy the workspace.',everyday,'projects','Use a supported sidebar and account. Confirm the specific task before reorganizing it.',4),
 entry('search-tasks','Find previous work','Workspace','Search tasks to reopen prior work; Find in chat searches within an already open conversation. These are different search scopes.','Find the task where we investigated the onboarding save defect, then summarize its verified result.',['Desktop'],'reference/commands','Search matching and shortcut assignments depend on the app version.',4),
 entry('commands','Commands and shortcuts','Workspace','The command menu helps discover actions. Slash-command availability depends on the current surface and access.','Show the available commands relevant to reviewing changes and checking this task’s status.',local,'reference/slash-commands','Type / to inspect commands available in your current composer.',4),
 entry('steering','Steer work already running','Workspace','Add a correction or new constraint to the active task while preserving its intended result. Goal controls can pause, resume, or edit the objective.','Keep building the checklist. Use French for the final copy and retain the same acceptance checks.',local,'long-running-work','Keep the task and its execution environment available.',6),
 entry('goals','Give long work a finish line','Workspace','Goal mode continues toward an explicit objective. A useful goal includes constraints and evidence that would establish completion.','Work toward a verified onboarding workspace. Keep the source brief intact, test the saved output, and report the actual deliverables.',local,'long-running-work','Goal mode keeps the task’s existing access and approval boundaries.',11),
 entry('activity','Activity and notifications','Workspace','Use activity and notification controls to find work that has finished or needs attention. Delivery channels vary by surface.','Show tasks waiting for my input, then summarize the specific decision each one needs.',['Desktop','Web','CLI','IDE'],'notifications','Activity view, operating-system permission and notification options vary.',10),
 entry('astra','GPT-6 Astra','Models','The documented choice for demanding workflows spanning code, apps and research. Give it sources, constraints and checks.','Investigate this multi-module failure, implement a repair, and verify the actual user journey.',local.concat('Web'),'models','Must appear in your account’s picker. Rollout, plan and sign-in method matter.',2),
 entry('sol','GPT-5.6 Sol','Models','A depth-oriented choice for difficult, ambiguous work that benefits from analysis and polish.','Review the architecture options against our constraints and test the recommended approach.',local.concat('Web','Cloud'),'models','Check current model availability and the execution surface.',2),
 entry('terra','GPT-5.6 Terra','Models','An everyday option for work needing sound reasoning and tool use.','Update the onboarding record from the brief, run the acceptance check, and show the saved result.',local.concat('Web'),'models','Select an available model in your current client.',2),
 entry('luna','GPT-5.6 Luna','Models','Suited to clear, repeatable tasks with well-defined outputs.','Extract the required fields from these fictional briefs into this exact CSV schema.',local.concat('Web'),'models','Use a representative sample and check output quality before scaling the task.',2),
 entry('spark','GPT-5.3 Codex Spark','Models','A text-only research preview focused on very fast coding iteration. The docs list Pro access.','Make this small text-only code change and run its focused check.',local,'models','Check preview availability. This card does not imply image input, API access, or cloud support.',2),
 entry('gpt55','GPT-5.5','Models','A previous-generation option still listed in the model documentation.','Run a familiar task with the available model and compare the checked result with your usual workflow.',local.concat('Web'),'models','Check the current picker; saved configurations can outlast model availability.',2),
 entry('effort','Model and effort are separate','Models','Effort changes how much reasoning is allocated. Start appropriately and increase it when deeper work is needed; more effort can use more time and tokens.','Recommend an available model and effort for this task, explaining the reasoning burden and the check you will use.',local.concat('Web'),'models','Picker labels and supported effort levels differ by model and client.',2),
 entry('max-ultra','Max and Ultra','Models','Max allocates more reasoning time to a task. Ultra uses subagents for suitable parallel work. Most tasks need neither.','Identify whether this problem needs deeper single-task reasoning or has independent parts worth delegating.',local.concat('Web'),'models','Options may need enabling and differ by account. Parallel work needs explicit division and integration.',2),
 entry('usage','Usage, tokens and credits','Models','Usage depends on the model, context, reasoning and tool work. Prompt length alone is not a reliable estimate. Check your actual usage view.','Check my current usage and reset timing. Then recommend a task scope that fits the remaining allowance.',local.concat('Web'),'pricing','Account-specific limits and credit rules apply; this guide contains no fixed price or speed estimate.',2),
 entry('instructions','AGENTS.md scope','Context','Codex combines applicable global and project guidance. More specific project instructions can refine broader guidance.','List the applicable AGENTS.md files and summarize the build, test and output requirements for this folder.',local,'agent-configuration/agents-md','File discovery depends on the working directory and configured guidance files.',1),
 entry('source-context','Relevant source files','Context','Provide current source data, the required output shape and review criteria. Make conflicting or obsolete inputs explicit.','Use the current client brief and sample CSV. Identify stale sources before changing the onboarding record.',everyday.concat('CLI','IDE'),'artifacts-viewer','The source files must be attached or accessible to the selected task.',1),
 entry('image-context','Screenshots as context','Context','An image is useful when the task depends on appearance. Explain what to inspect and what result you want.','Compare this screenshot with the actual page and identify the layout mismatch before proposing a repair.',local.concat('Web'),'image-inputs','Use an image-capable model and a supported attachment or image-reading path.',1),
 entry('appshots','Bring an app window into context','Context','Appshots attach the frontmost Mac window as an image with available text. They provide context for a request.','Use this appshot to identify the visible error and propose the next diagnostic step.',['Desktop'],'appshots','macOS Appshots enablement and required permissions. Captured content can include available text beyond the visible area.',1),
 entry('memories','Memory versus required guidance','Context','Local Codex memories and ChatGPT web memory have separate stores and controls. Keep required project rules in explicit guidance.','Explain which memory controls apply here. Put the durable project requirements in AGENTS.md.',local.concat('Web'),'customization/memories','Memory availability and settings vary. Recall is not a substitute for the current source of truth.',1),
 entry('context-management','Experimental context management','Context','Supported Astra clients can keep notes and search earlier messages and tool results within the same task across context windows.','Check whether experimental context management is available in my client and account before suggesting a configuration change.',local,'models','The documented launch scope is ChatGPT Plus/Pro on supported clients; opt-in is off by default and requires a new task.',1),
 entry('skills','A skill preserves a procedure','Tools','A skill packages task-specific instructions, resources and optional scripts. Its description helps the agent determine when it applies.','Turn the verified onboarding procedure into a skill with inputs, steps, checks, output and failure behavior.',local.concat('Web'),'build-skills','Standalone and plugin-bundled skills have different distribution surfaces.',8),
 entry('plugins','A plugin distributes capabilities','Tools','Plugins can bundle skills, MCP servers and hooks. Installation, connection and available actions are separate things to inspect.','Identify the plugin needed to read this source, and check its connection and scope before using it.',['Desktop','Web','CLI','Mobile'],'plugins','Some plugins are desktop-only. The docs do not list plugin support in the IDE extension.',8),
 entry('mcp','MCP connects tools and context','Tools','Local Codex clients can connect to MCP servers. Web workflows can use remote MCP-backed tools through supported plugins.','List the tools exposed by the connected document service and use the appropriate read action for the brief.',local.concat('Web'),'extend/mcp','A configured server or supported plugin, successful authentication, and available tool permissions are required.',8),
 entry('browser','Use the real browser','Tools','Open pages, inspect rendered results and perform a user journey. The built-in browser is documented for desktop and web.','Open the page, save a record, reload it, and verify the persisted result against the brief.',everyday,'browser','The built-in browser is not a CLI/IDE feature. Managed settings can restrict browser actions.',9),
 entry('computer-use','Operate a graphical app','Tools','Computer Use can inspect and operate supported desktop interfaces when a direct integration does not cover the task.','Inspect the desktop app’s export dialog and verify that the requested file was created.',['Desktop'],'computer-use','Supported region/OS, the Computer Use plugin, and required system permissions.',9),
 entry('search-web','Search for current evidence','Tools','Search brings current sources into the task. Treat retrieved material as source content, not instructions that redefine the job.','Find the current official documentation for this setting and distinguish documented behavior from assumptions.',local.concat('Web'),'web-search','Search must be available under the client and workspace configuration.',1),
 entry('artifacts','Create and inspect files','Tools','Specify a file type, structure and checks. Preview the actual output and request focused revisions where supported.','Create the onboarding handoff as an editable document and inspect the exported PDF for missing or clipped content.',everyday.concat('CLI','IDE'),'artifacts-viewer','Desktop previews depend on file type. CLI creates files but has no visual preview UI; IDE documents need a compatible viewer.',11),
 entry('image-generation','Generate and revise images','Tools','Create assets from a brief or revise reference images. State the intended use and what must stay consistent.','Create a fictional onboarding illustration in this visual style, then revise only the background after inspection.',local.concat('Web'),'image-generation','An available image-generation feature and applicable usage allowance.',8),
 entry('sites','Hosted Sites','Tools','Sites can create, host and refine compatible websites, apps and games. Publishing has its own versions, access and usage controls.','Build a small status page, verify its main journey, then prepare the hosted version for review.',everyday,'sites','Sites is a beta feature with plan and usage conditions. This game’s planned host is separately here.now.',11),
 entry('visualizations','Interactive explanations','Tools','A visualization can turn a comparison or relationship into an interactive chart, diagram or simulation.','Make an interactive explanation of how source quality and missing tools affect an onboarding workflow.',everyday,'visualizations','The Visualizations preview must be available to the account and surface.',0),
 entry('permissions','Access and approval boundaries','Tools','The execution environment and approval policy control different parts of an action. Identify the specific missing access before changing settings.','Diagnose why this file cannot be read and describe the smallest relevant access change.',local,'agent-approvals-security','Current sandbox, network and workspace requirements apply. Tool capability is not permission to send or publish.',3),
 entry('review','Review the actual changes','Delivery','Choose the diff scope you mean to inspect. A repository view can contain changes from outside the latest task.','Review the last turn’s changes against the brief and identify concrete defects with file references.',local.concat('Web'),'code-review','Make the intended files, branch or diff available and state review criteria.',7),
 entry('worktrees','Independent working files','Delivery','Git worktrees provide separate checkouts while sharing repository metadata. Compare and verify changes before integration.','Use separate worktrees for two competing implementations. Define ownership and compare their tested results.',local,'environments/git-worktrees','A Git repository and suitable environment setup. External services are not automatically isolated.',5),
 entry('handoff','Move work between checkouts','Delivery','Handoff moves the task and associated code between Local and Worktree in supported desktop workflows.','Inspect the current Git state, then prepare this worktree’s changes for handoff to the local checkout.',['Desktop'],'environments/git-worktrees','Checkouts and branches must be reconciled. Handoff is not the same as publishing a release.',5),
 entry('subagents','Delegate independent parts','Delivery','Subagents can handle bounded pieces of a task and return results for integration. Clear ownership prevents overlapping edits.','Use one subagent to inspect test gaps and another to review the data flow. Wait for both and reconcile their findings.',local.concat('Web'),'agent-configuration/subagents','Supported clients and access; ask explicitly where required. Delegation consumes additional model/tool work.',5),
 entry('schedules','Schedule a tested workflow','Delivery','Recurring tasks need a defined procedure and reporting condition. Local scheduled work needs its computer and app available.','Run this verified local check every weekday at 9 AM in my timezone; notify me only of actionable changes.',['Desktop','Web','Mobile'],'automations','Execution and trigger support differ across local and hosted tasks. Verify inputs and runtime availability.',10),
 entry('cli','Work from the terminal','Developer','The CLI can inspect a repository, edit files and run commands. Non-interactive execution can fit repeatable workflows.','Inspect this repository, make the requested change, and run its meaningful checks.', ['CLI'],'cli','Install and authenticate Codex; start in the intended directory and permission scope.',0),
 entry('ide','Work beside your code','Developer','The IDE extension can use selected code and open files as context while you review changes in the editor.','Use the selected function and its callers to reproduce this defect and propose a minimal repair.',['IDE'],'ide','A supported editor, installed extension and authentication.',1),
 entry('cloud','An isolated cloud environment','Developer','Codex cloud runs coding tasks in configured remote environments. Reproducible setup and review remain part of the workflow.','Set up the repository’s dependencies, run the task in its cloud environment, then review the diff and check results.',['Cloud'],'cloud','A connected repository, supported account and configured cloud environment.',5),
 entry('remote','Your phone controls a host','Developer','Remote lets the mobile app guide tasks running on a connected computer. The phone is the control surface.','Show progress for the onboarding task on my connected computer and identify any decision waiting for me.',['Mobile','Desktop'],'remote','Connected supported computer, mobile setup, rollout and workspace access. The repository stays on the host.',10),
 entry('configuration','Know which config applies','Developer','Personal settings and trusted project configuration can form layers. Inspect the effective scope before editing a default.','Explain which configuration files affect this task and identify the specific setting responsible for the behavior.',local,'config-file/config-basic','Project configuration is loaded only under applicable trust and managed requirements.',3),
 entry('hooks','Checks at lifecycle events','Developer','Hooks run configured scripts or MCP tools at points in the agent loop. They are executable behavior, unlike a prose reminder.','Design a narrowly scoped validation hook, explain its event and output, then test it in an isolated sample.',local,'hooks','Configured, reviewed and trusted hooks under applicable client and managed-policy rules.',8),
 entry('sdk','Automate with the Codex SDK','Developer','Use the SDK to integrate Codex tasks into programs, internal workflows or CI.','Build a small local example that runs a bounded review and records structured task events.',['CLI'],'codex-sdk','Developer integration with the documented SDK, authentication and a suitable runtime.',11),
 entry('app-server','Build a richer client','Developer','App-server supports clients that manage task history, authentication, approvals and streamed agent events.','Explain the app-server lifecycle for a custom review client and identify the events the UI needs.',['Desktop','IDE','CLI'],'app-server','An advanced client integration; follow the protocol and current experimental-feature boundaries.',0),
 entry('troubleshooting','Check the right failure surface','Developer','Use the actual task, repository and environment state to diagnose a problem. For example, the review pane may show pre-existing edits.','Explain why this diff contains a file the task did not edit. Compare the Last turn and repository views.',['Desktop'],'reference/troubleshooting','Reproduce the behavior in the affected client and retain the relevant evidence.',7),
];

atlas.push({...entry('ask-for-workspace','Ask for a task with chosen effort','Workspace','Mark’s installation exposes task creation with model/effort settings and sidebar organization. A prompt can request those actions together.','Create a separate task in this project using GPT-6 Astra at high effort. Ask it to review the onboarding checklist against the client brief. Name it “Onboarding review” and pin it.',['Desktop'],'projects','Requires those task-management capabilities in your installation and an available model/effort combination.',4),claim:'installation',evidence:'Task-creation and sidebar-management tool definitions were exposed in this production session. This is not a fresh execution test or a universal availability claim.'});
atlas.push({...entry('fork-task','Branch a conversation','Workspace','A supported conversation fork can reuse completed history for another direction. File isolation is a separate choice.','Fork this task to explore a different explanation using the completed conversation. Keep the original task available.',['Desktop'],'app-server','The installation must expose conversation forking; verify whether the chosen fork also changes checkout.',5),claim:'installation',evidence:'Fork capability is exposed on Mark’s installation. The app-server source documents the related protocol; exact UI and tool behavior are installation-specific.'});

export function searchAtlas(query='',category='all',surface='all'){
 const words=query.toLocaleLowerCase().trim().split(/\s+/).filter(Boolean);
 return atlas.filter(e=>(category==='all'||e.category===category)&&(surface==='all'||e.surfaces.includes(surface))&&words.every(w=>`${e.title} ${e.summary} ${e.example} ${e.prerequisites}`.toLocaleLowerCase().includes(w)));
}
export function atlasMarkdown(){return `# Inside Codex field notes\n\nChecked ${ATLAS_DATE}. These are dated capability notes and suggested practice requests. Availability can differ by client, account, rollout, configuration and connected tools.\n\n${atlas.map(e=>`## ${e.title}\n\n${e.summary}\n\nTry: ${e.example}\n\nSurfaces: ${e.surfaces.join(', ')}\n\nRequires: ${e.prerequisites}\n\nEvidence: ${e.claim==='official'?'Official documentation':'Installation capability'} — ${e.evidence}\n\nSource: ${e.source}\nChecked: ${e.verifiedAt}`).join('\n\n')}\n`;}
