export const initialClock=Date.parse('2026-09-10T12:55:00Z');
export const automationPrompts={vague:'Keep an eye on onboarding. Let me know how it looks.',durable:'Every weekday at 09:00 America/Toronto, return to this task. Read the current local Northstar onboarding CSV. Check whether approval_owner is missing. Save a dated report with the source values and compare its actionable findings with the last successful run. Report new missing approvals, resolutions and new read failures; stay quiet when nothing actionable changes. Preserve the last successful baseline when a read fails. Do not edit the source or send email.'};
export const automationSources={approved:{client:'Northstar Studio',approval_owner:'Nina Patel'},missing:{client:'Northstar Studio',approval_owner:''},unavailable:null};
const formatters=new Map();
export function clockParts(time,zone){if(!formatters.has(zone))formatters.set(zone,new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}));return Object.fromEntries(formatters.get(zone).formatToParts(new Date(time)).filter(p=>p.type!=='literal').map(p=>[p.type,Number(p.value)]));}
export function displayClock(time,zone='America/Toronto'){const p=clockParts(time,zone);return `${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][new Date(Date.UTC(p.year,p.month-1,p.day)).getUTCDay()]} ${p.year}-${String(p.month).padStart(2,'0')}-${String(p.day).padStart(2,'0')} ${String(p.hour).padStart(2,'0')}:${String(p.minute).padStart(2,'0')} · ${zone}`;}
export function nextAutomationDue(now,config){const local=clockParts(now,config.timezone);for(let add=0;add<9;add++){const day=new Date(Date.UTC(local.year,local.month-1,local.day+add,12));if(config.cadence==='weekdays'&&[0,6].includes(day.getUTCDay()))continue;const desired=Date.UTC(day.getUTCFullYear(),day.getUTCMonth(),day.getUTCDate(),Number(config.hour));let candidate=desired;for(let n=0;n<3;n++){const p=clockParts(candidate,config.timezone);candidate+=desired-Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute);}if(candidate>now)return candidate;}return null;}
export const freshAutomation=()=>({section:'setup',now:initialClock,config:{prompt:'vague',cadence:'weekdays',hour:'9',timezone:'America/Toronto',destination:'same',notifications:'changes',onFailure:'report'},revision:1,testedVersion:null,enabled:false,host:true,source:'approved',baseline:null,lastFailure:null,runs:[],events:[],actions:[],nextId:1,message:'The local brief is ready. Test a precise prompt before turning on the weekday schedule. The rehearsal clock starts Thursday at 08:55 Toronto time.'});
const note=(s,message)=>{s.message=message;s.events.push(message);s.events=s.events.slice(-60);};
const choices={prompt:['vague','durable'],cadence:['weekdays','daily'],hour:['9','15'],timezone:['America/Toronto','UTC'],destination:['same','new'],notifications:['changes','every'],onFailure:['report','quiet']};
function execute(s,kind,time){const run={id:s.nextId++,kind,time,revision:s.revision,destination:s.config.destination,status:'',notification:false,reason:'',source:null,report:null};
 if(!s.host){run.status='host-unavailable';run.reason='Local computer/app unavailable. No task executed and no in-task notification was sent.';s.runs.push(run);note(s,run.reason);return;}
 if(s.config.prompt!=='durable'){run.status='unclear';run.reason='No defined source, acceptance check or reporting condition. Test a durable prompt.';s.runs.push(run);note(s,run.reason);return;}
 if(s.source==='unavailable'){run.status='read-failed';run.reason='Current local CSV could not be read. Last successful baseline preserved.';run.notification=kind==='scheduled'&&s.config.onFailure==='report'&&s.lastFailure!=='read';s.lastFailure='read';s.runs.push(run);note(s,run.reason+(run.notification?' New failure reported.':' No notification.'));return;}
 const source={...automationSources[s.source]},finding=source.approval_owner?'clear':'missing-approval',previous=s.baseline;run.status='success';run.source=source;run.report={client:source.client,approval_owner:source.approval_owner,finding,previous:previous?.finding??null,recovered:s.lastFailure==='read'};
 const changed=previous?previous.finding!==finding:finding!=='clear';run.notification=kind==='scheduled'&&(s.config.notifications==='every'||changed||run.report.recovered);
 run.reason=kind==='manual'?'Manual test saved a checked report. No scheduled notification.':run.notification?(run.report.recovered?'Source access recovered.':finding==='missing-approval'?'Missing approval needs attention.':changed?'Approval restored; issue resolved.':'Routine notification, although nothing actionable changed.'):'Successful check; nothing actionable changed. Stay quiet.';
 s.baseline={finding,source,time};s.lastFailure=null;if(kind==='manual')s.testedVersion=s.revision;s.runs.push(run);note(s,run.reason);
}
const names=['config','test','enable','pause','host','source','advance'];
export function automationAction(input,action,value){if(action==='restart')return freshAutomation();const s=structuredClone(input);if(action==='section'&&['setup','clock','runs'].includes(value)){s.section=value;return s;}if(!names.includes(action))return s;
 let field,choice;if(action==='config'){[field,choice]=String(value).split(':');if(!choices[field]?.includes(choice))return s;}
 if(action==='host'&&!['on','off'].includes(value))return s;if(action==='source'&&!Object.hasOwn(automationSources,value))return s;if(action==='advance'&&!['5m','day'].includes(value))return s;
 if(s.actions.length>=180){s.message='This rehearsal has reached its history limit. Restart to explore another sequence.';return s;}s.actions.push({action,...(value===undefined?{}:{value})});
 if(action==='config'){if(s.config[field]!==choice){s.config[field]=choice;s.revision++;s.testedVersion=null;s.enabled=false;s.baseline=null;s.lastFailure=null;}note(s,'Setup updated. Retest this revision before enabling it; earlier run records remain available.');}
 if(action==='test')execute(s,'manual',s.now);
 if(action==='enable'){if(s.testedVersion!==s.revision){note(s,'Test the current setup successfully before enabling its schedule.');return s;}s.enabled=true;note(s,'Schedule enabled in the rehearsal. Next due: '+displayClock(nextAutomationDue(s.now,s.config),s.config.timezone)+'.');}
 if(action==='pause'){s.enabled=false;note(s,'Schedule paused. Advancing the clock will not execute it.');}
 if(action==='host'){s.host=value==='on';note(s,s.host?'Local computer and app are available. Future due times can run.':'Local computer/app is unavailable. The simulator can show missed runs; the offline task itself cannot report them.');}
 if(action==='source'){s.source=value;note(s,value==='unavailable'?'Fixture changed: source file is unavailable. A failed read must not become an “all clear”.':value==='missing'?'Fixture changed: the approval owner is now missing. The next successful read will see it.':'Fixture changed: Nina Patel is the approval owner.');}
 if(action==='advance'){const end=s.now+(value==='5m'?300000:86400000);let due=nextAutomationDue(s.now,s.config),count=0;if(s.enabled)while(due!==null&&due<=end){execute(s,'scheduled',due);count++;due=nextAutomationDue(due,s.config);}s.now=end;if(!count)note(s,s.enabled?'Clock advanced. No run was due in this interval.':'Clock advanced while paused. No run executed.');s.message=displayClock(s.now)+' — '+s.message;}
 return s;}
export function automationChecks(s){const runs=s.runs.filter(r=>r.revision===s.revision&&r.kind==='scheduled'),ok=r=>r.status==='success';return [
 {name:'Tested weekday 09:00 Toronto setup returns to this task',pass:s.testedVersion===s.revision&&s.config.prompt==='durable'&&s.config.cadence==='weekdays'&&s.config.hour==='9'&&s.config.timezone==='America/Toronto'&&s.config.destination==='same'&&s.config.notifications==='changes'&&s.config.onFailure==='report'},
 {name:'Unchanged successful run stayed quiet',pass:runs.some(r=>ok(r)&&!r.notification)},
 {name:'New missing approval produced a finding',pass:runs.some(r=>ok(r)&&r.report.finding==='missing-approval'&&r.notification)},
 {name:'Read failure was reported without overwriting the baseline',pass:runs.some(r=>r.status==='read-failed'&&r.notification)},
 {name:'Recovered source produced a checked resolution',pass:runs.some(r=>ok(r)&&r.report.recovered&&r.report.finding==='clear'&&r.notification)},
 {name:'Offline host was observed without claiming a task ran',pass:runs.some(r=>r.status==='host-unavailable'&&!r.notification)},
 {name:'Recovered setup ran successfully and remains active',pass:s.enabled&&s.host&&s.source!=='unavailable'&&s.baseline?.finding==='clear'&&s.lastFailure===null&&runs.at(-1)?.status==='success'&&runs.at(-1)?.report.finding==='clear'}
 ];}
export const automationPass=s=>!!s&&automationChecks(s).every(c=>c.pass===true);
export const automationReceipt=s=>automationPass(s)?{version:1,simulation:true,actions:s.actions,config:s.config,now:s.now,runs:s.runs,baseline:s.baseline,checks:automationChecks(s)}:null;
export function normalizeAutomationReceipt(r){if(r?.version!==1||r.simulation!==true||!Array.isArray(r.actions)||r.actions.length>180)return null;let s=freshAutomation();for(const a of r.actions){if(!a||!names.includes(a.action)||Object.keys(a).some(k=>!['action','value'].includes(k))||(a.value!==undefined&&(typeof a.value!=='string'||a.value.length>40)))return null;s=automationAction(s,a.action,a.value);}const expected=automationReceipt(s);const candidate=structuredClone(r);if(candidate.checks?.[6]?.name==='Schedule is active with accessible source and host')candidate.checks[6].name='Recovered setup ran successfully and remains active';return expected&&JSON.stringify(expected)===JSON.stringify(candidate)?expected:null;}
export function automationFiles(r){return {'automation-tower/MY-SCHEDULE.md':`# A tested recurring check\n\n${automationPrompts.durable}\n\nExecution: local computer powered on, desktop app running, current project/source accessible. Keep applicable sandbox restrictions. Review the first few real runs and adjust the prompt or cadence when needed.\n\nThis game created no real scheduled task. Ask Codex to create it in the current task, then review the resulting schedule and next run in your app. The exported dates below are simulated history.\n\n${r.checks.map(c=>'- '+c.name+': observed').join('\n')}\n\nOfficial source, checked September 10, 2026: https://learn.chatgpt.com/docs/automations\n`,'automation-tower/simulated-runs.json':JSON.stringify(r.runs,null,2)+'\n','automation-tower/rehearsal.json':JSON.stringify(r,null,2)+'\n','automation-tower/latest-report.json':JSON.stringify(r.runs.filter(x=>x.status==='success').at(-1).report,null,2)+'\n','automation-tower/READ-ME.md':'# Read the evidence\n\nThe game advances a synthetic clock. Scheduled runs use fixed CSV fields and deterministic notification logic. They do not reproduce actual Codex timing, scheduler catch-up policy, model output or operating-system notification delivery. Offline-host entries are observations by the simulator, not notifications sent by a powered-off computer. The replay skips missed runs; real catch-up behavior is not asserted.\n\nA quiet successful check is different from a read failure. Failure preserves the previous successful baseline. A recovered source is reported once, and subsequent unchanged results are quiet. This deduplication is implemented by the exercise procedure, not a claim that Codex automatically deduplicates every notification.\n\nA standalone task can also preserve state in accessible files. This brief requests the existing task; the exercise does not claim standalone tasks inherently lack persistent state.\n'};}
