import {Scene} from '@babylonjs/core/scene';import {TransformNode} from '@babylonjs/core/Meshes/transformNode';import {MeshBuilder} from '@babylonjs/core/Meshes/meshBuilder';import {Vector3,Matrix} from '@babylonjs/core/Maths/math.vector';import {Color3} from '@babylonjs/core/Maths/math.color';import {PBRMaterial} from '@babylonjs/core/Materials/PBR/pbrMaterial';import {StandardMaterial} from '@babylonjs/core/Materials/standardMaterial';import {DynamicTexture} from '@babylonjs/core/Materials/Textures/dynamicTexture';import {ActionManager} from '@babylonjs/core/Actions/actionManager';import {ExecuteCodeAction} from '@babylonjs/core/Actions/directActions';import {freshAutomation,automationPass,clockParts} from './automation-lab.mjs';
export function buildAutomationExhibit(scene:Scene,anchor:Vector3,onAction:(id:string)=>void){
 const root=new TransformNode('Automation tower clockwork',scene);root.position=anchor.clone();
 const material=(name:string,color:string,metal=0)=>{const m=new PBRMaterial(name,scene);m.albedoColor=Color3.FromHexString(color);m.metallic=metal;m.roughness=.31;return m;};
 const ivory=material('Automation porcelain','#eae4d7'),graphite=material('Automation graphite','#343c37'),metal=material('Automation brushed brass','#b2a487',.7),purple=material('Automation hands','#8264a2');
 function box(name:string,x:number,y:number,z:number,w:number,h:number,d:number,m:PBRMaterial){const b=MeshBuilder.CreateBox(name,{width:w,height:h,depth:d},scene);b.parent=root;b.position.set(x,y,z);b.material=m;b.isPickable=false;return b;}
 box('Clock base',0,1.56,0,2.65,.16,.75,metal);box('Clock tower backplate',0,2.24,-.12,2.42,1.29,.16,graphite);
 ivory.backFaceCulling=false;
 const rim=MeshBuilder.CreateTorus('Clock rim',{diameter:1.12,thickness:.055,tessellation:64},scene);rim.parent=root;rim.position.set(-.58,2.25,.04);rim.rotation.x=Math.PI/2;rim.material=metal;rim.isPickable=false;
 const dial=MeshBuilder.CreateDisc('Clock dial',{radius:.53,tessellation:64},scene);dial.parent=root;dial.position.set(-.58,2.25,.065);dial.material=ivory;dial.isPickable=false;
 for(let i=0;i<12;i++){const a=i*Math.PI/6;const tick=box('Clock tick '+i,-.58+Math.sin(a)*.44,2.25+Math.cos(a)*.44,.095,.018,i%3===0?.10:.045,.015,graphite);tick.rotation.z=-a;}
 const pivot=new TransformNode('Hour pivot',scene);pivot.parent=root;pivot.position.set(-.58,2.25,.14);const hand=box('Hour hand',0,.15,0,.055,.35,.035,purple);hand.parent=pivot;
 const minutes=new TransformNode('Minute pivot',scene);minutes.parent=root;minutes.position.set(-.58,2.25,.16);const minute=box('Minute hand',0,.19,0,.028,.44,.025,graphite);minute.parent=minutes;
 function plate(id:string,x:number,y:number,w:number,h:number,tw=512,th=224){const texture=new DynamicTexture('Automation '+id,{width:tw,height:th},scene,true),m=new StandardMaterial('Automation ink '+id,scene);m.diffuseTexture=texture;m.emissiveColor=Color3.White();m.disableLighting=true;m.backFaceCulling=false;const face=MeshBuilder.CreatePlane('Automation '+id,{width:w,height:h},scene);face.parent=root;face.position.set(x,y,.22);face.material=m;return {id,texture,face};}
 const ports=[['setup','SETUP'],['clock','REHEARSE'],['runs','EVIDENCE']].map(([id,label],i)=>{const p=plate(id,(i-1)*.86,3.08,.8,.34);p.face.actionManager=new ActionManager(scene);p.face.actionManager.registerAction(new ExecuteCodeAction(ActionManager.OnPickTrigger,()=>onAction(id)));return {...p,label};});
 const status=plate('clock status',0,2.82,2.15,.17,1024,88);status.face.isPickable=false;
 const rows=[0,1,2].map(i=>{const p=plate('run '+i,.65,2.55-i*.28,.91,.21,512,118);p.face.isPickable=false;return p;});
 const time=plate('local time',-.58,1.72,1.1,.13,512,64);time.face.isPickable=false;
 let s:any=freshAutomation(),sig='',targetHour=0,targetMinute=0;
 function setState(next:any){s=next;const key=JSON.stringify([s.section,s.now,s.config,s.enabled,s.host,s.runs]);if(key===sig)return;sig=key;const p=clockParts(s.now,s.config.timezone);targetHour=-((p.hour%12)+p.minute/60)*Math.PI/6;targetMinute=-p.minute*Math.PI/30;
  for(const port of ports){const c=port.texture.getContext() as CanvasRenderingContext2D;c.fillStyle=port.id===s.section?'#51436a':'#eae5da';c.fillRect(0,0,512,224);c.fillStyle=port.id===s.section?'#f4f0e5':'#343b35';c.font='bold 56px sans-serif';c.textAlign='center';c.fillText(port.label,256,100);c.font='29px sans-serif';c.fillText(port.id==='setup'?'TEST THE PROMPT':port.id==='clock'?'ADVANCE THE CLOCK':'READ THE RUNS',256,168);port.texture.update();}
  const c=status.texture.getContext() as CanvasRenderingContext2D;c.fillStyle=automationPass(s)?'#36573c':'#343c37';c.fillRect(0,0,1024,88);c.fillStyle='#eee9dd';c.font='bold 36px sans-serif';c.textAlign='center';c.fillText((s.enabled?'ACTIVE':'PAUSED')+' · '+(s.config.timezone==='UTC'?'UTC':'TORONTO')+' · '+(s.host?'HOST AVAILABLE':'HOST OFFLINE'),512,59);status.texture.update();
  const tc=time.texture.getContext() as CanvasRenderingContext2D;tc.fillStyle='#343c37';tc.fillRect(0,0,512,64);tc.fillStyle='#eee9dd';tc.textAlign='center';tc.font='bold 42px sans-serif';tc.fillText(String(p.hour).padStart(2,'0')+':'+String(p.minute).padStart(2,'0'),256,47);time.texture.update();
  rows.forEach((row,i)=>{const r=[...s.runs].reverse()[i],ctx=row.texture.getContext() as CanvasRenderingContext2D;ctx.fillStyle=!r?'#50534a':r.status==='host-unavailable'?'#655b50':['read-failed','unclear'].includes(r.status)?'#85534a':r.notification?'#806644':'#48664c';ctx.fillRect(0,0,512,118);ctx.fillStyle='#f2eddf';ctx.font='bold 36px sans-serif';ctx.textAlign='center';ctx.fillText(!r?'WAITING':r.status==='host-unavailable'?'HOST OFFLINE':r.status==='read-failed'?'READ FAILED':r.status==='unclear'?'DEFINE THE JOB':r.kind==='manual'?'MANUAL TEST':r.notification?'FINDING':'QUIET SUCCESS',256,72);row.texture.update();});
 }
 setState(s);
 return {setState,update:(dt:number,reduced:boolean)=>{for(const [node,target] of [[pivot,targetHour],[minutes,targetMinute]] as const){let delta=((target-node.rotation.z+Math.PI)%(2*Math.PI)+2*Math.PI)%(2*Math.PI)-Math.PI;node.rotation.z=reduced?target:node.rotation.z+delta*Math.min(1,dt*7);}},state:()=>({verified:automationPass(s),enabled:s.enabled,hourAngle:pivot.rotation.z,targetHour,runCount:s.runs.length,ports:ports.map(p=>{const e=scene.getEngine(),v=scene.activeCamera!.viewport.toGlobal(e.getRenderWidth(),e.getRenderHeight());v.y=e.getRenderHeight()-v.y-v.height;const q=Vector3.Project(p.face.getAbsolutePosition(),Matrix.Identity(),scene.getTransformMatrix(),v);return {id:p.id,screen:{x:q.x*e.getRenderingCanvas()!.clientWidth/e.getRenderWidth(),y:q.y*e.getRenderingCanvas()!.clientHeight/e.getRenderHeight()}};})})};
}
