import {browserDepthStage} from './browser-depth.mjs';
const esc=(v:unknown)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function browserDepthView(s:any,playing:boolean,paused:boolean,reduced:boolean){
 const l=s.lab,stage=browserDepthStage(s),done=stage==='verified';
 const titles:Record<string,string>={ready:'What does “Saved” prove?',saved:'The page says yes. The record says no.',reproduced:'You found the missing write.',repaired:'Now test the same path again.',verified:'It survives. That’s your proof.'};
 const guide:Record<string,string>={ready:'A success message is one clue. Follow the value through all three layers to find out what really happened.',saved:'The name reached the page, but the saved record is empty. Reload the page to expose the difference.',reproduced:'The reload reads the saved record. Nothing was written there, so the name disappeared. Repair that one connection.',repaired:'A repair still needs evidence. Save Nina Patel again, reload, and compare the result with the brief.',verified:'The visible page and saved record agree after a reload. Take this habit into Codex: repeat the original steps and inspect the result.'};
 const next=stage==='ready'?['save','Save owner →']:stage==='saved'?['reload','Reload the page →']:stage==='reproduced'?['repair','Connect save to record →']:done?['download','Download evidence ↓']:l.record&&l.savedRecord&&l.input.trim()===l.savedRecord?['reload','Reload and verify →']:['save','Save owner again →'];
 return `<section class="depth-shell browser-depth" aria-label="Inside the Browser Lab">
 <nav class="depth-breadcrumb" aria-label="Exploration breadcrumb"><button data-action="depth-close">Browser Lab</button><span>/</span><strong>Inside a save</strong></nav>
 <div class="depth-scene-title"><span>EXPLORE INSIDE / 10</span><h1>Follow a save.</h1><p>Page. Action. Saved record.</p></div>
 <aside class="depth-inspector"><header><span>THE BROWSER LAB</span><button data-action="depth-close" aria-label="Return to station">↶ Return to station</button></header>
 <nav class="depth-tabs" aria-label="Inspection points">${[['page','01 Page'],['action','02 Action'],['record','03 Record']].map(([id,label])=>`<button data-action="depth-focus" data-value="${id}" aria-pressed="${s.focus===id}">${label}</button>`).join('')}</nav>
 <div class="depth-content" tabindex="0" aria-label="Save inspector"><div class="browser-stage ${done?'is-verified':''}">${done?'VERIFIED AFTER RELOAD':stage==='reproduced'?'DEFECT REPRODUCED':l.fixed?'REPAIR UNDER TEST':'PERSISTENCE EXPERIMENT'}</div><h2 tabindex="-1">${titles[stage]}</h2>
 <p class="browser-brief">The client brief names <strong>Nina Patel</strong> as the approval owner.</p>
 <div class="browser-mini-page"><div class="browser-chrome"><i></i><i></i><i></i><span>northstar / approval</span></div><label for="depth-owner">Approval owner</label><input id="depth-owner" maxlength="80" autocomplete="off" value="${esc(l.input)}" placeholder="Nina Patel"/><button data-action="depth-input" data-value="Nina Patel" class="browser-fill">Use name from brief</button><div class="browser-visible"><span>ON THE PAGE</span><strong>${esc(l.record||'No owner saved')}</strong></div></div>
 <div class="browser-inspection" aria-label="Selected layer"><span>${s.focus==='page'?'01 / PAGE':s.focus==='action'?'02 / SAVE ACTION':'03 / SAVED RECORD'}</span>${s.focus==='page'?`<p>The page displays <strong>${esc(l.record||'an empty record')}</strong>. A “Saved” message alone does not prove persistence.</p>`:s.focus==='action'?`<p>${l.fixed?'Save updates the page <strong>and writes to the saved record</strong>. Reload reads that record.':'Save updates the page and shows a success message. <strong>The write to the saved record is missing.</strong>'}</p><div class="browser-connection ${l.fixed?'connected':''}">Page <b>→</b> Save <b>${l.fixed?'→':'×'}</b> Record</div>`:`<p>Stored approval owner</p><strong class="browser-stored">${esc(l.savedRecord||'Empty')}</strong><small>${l.savedRecord?'This is the value a reload can read.':'A reload has nothing to restore.'}</small>`}</div>
 <p class="browser-status ${done?'is-verified':''}" role="status">${esc(l.message)}</p>
 <details class="browser-evidence" ${done?'open':''}><summary>Evidence trail <span>${s.events.length} events</span></summary>${s.events.length?`<ol>${s.events.map((e:any)=>`<li><strong>${esc(e.action.toUpperCase())}</strong><span>Page: ${esc(e.visible||'empty')} · Record: ${esc(e.stored||'empty')}</span></li>`).join('')}</ol>`:'<p>Save or reload to leave an observable result here.</p>'}<p class="depth-explanation">This is a simulation with an in-memory saved record. It makes no live network requests.</p></details>
 ${done?'<details class="browser-habit"><summary>Take this habit into Codex</summary><p>Ask Codex to reproduce the failure in the browser, inspect the save and persistence path, make the smallest repair, then repeat the original steps and report the observed result.</p></details>':''}
 </div><footer class="depth-actions"><button class="button-primary" data-action="depth-${next[0]}">${next[1]}</button><div class="browser-secondary"><button data-action="depth-example">${playing?'Stop example':'Play example'}</button><button data-action="depth-${next[0]==='reload'||next[0]==='download'?'save':'reload'}">${next[0]==='reload'||next[0]==='download'?'Save again':'Reload'}</button></div></footer></aside>
 <aside class="depth-guide"><img src="/assets/codex-reference.png" alt=""/><p>${guide[stage]}</p></aside>
 <footer class="depth-bottom"><span>Fictional Northstar simulation · Your exercise stays intact</span><div><button data-action="depth-motion">${reduced?'Motion off':'Motion on'}</button><button data-action="depth-pause">${paused?'Resume':'Pause'}</button><button data-action="depth-reset">Reset</button><button data-action="depth-close">Back / Esc</button></div></footer></section>`;
}
