import {Scene} from '@babylonjs/core/scene';import {TransformNode} from '@babylonjs/core/Meshes/transformNode';import {MeshBuilder} from '@babylonjs/core/Meshes/meshBuilder';import {Vector3,Matrix} from '@babylonjs/core/Maths/math.vector';import {Color3} from '@babylonjs/core/Maths/math.color';import {PBRMaterial} from '@babylonjs/core/Materials/PBR/pbrMaterial';import {StandardMaterial} from '@babylonjs/core/Materials/standardMaterial';import {DynamicTexture} from '@babylonjs/core/Materials/Textures/dynamicTexture';import {ActionManager} from '@babylonjs/core/Actions/actionManager';import {ExecuteCodeAction} from '@babylonjs/core/Actions/directActions';import {freshCapstone,capstoneRubric,capstonePass} from './capstone-lab.mjs';
export function buildCapstoneExhibit(scene:Scene,anchor:Vector3,onAction:(id:string)=>void){
 const root=new TransformNode('Cedar capstone workbench',scene);root.position=anchor.clone();root.setEnabled(false);
 const material=(name:string,hex:string,metallic=0)=>{const m=new PBRMaterial(name,scene);m.albedoColor=Color3.FromHexString(hex);m.roughness=.34;m.metallic=metallic;return m;};const ivory=material('Cedar mineral','#e8e1ce'),metal=material('Cedar metal','#a7a995',.65),ink=material('Cedar dark','#334338'),purple=material('Cedar working','#8272ad'),green=material('Cedar verified','#8fb487');
 const box=(name:string,x:number,y:number,z:number,w:number,h:number,d:number,m:PBRMaterial)=>{const b=MeshBuilder.CreateBox(name,{width:w,height:h,depth:d},scene);b.parent=root;b.position.set(x,y,z);b.material=m;b.isPickable=false;return b;};
 box('Cedar desk',0,1.57,0,2.68,.13,.92,metal);box('Cedar report backing',0,2.25,-.12,2.30,1.22,.18,ivory);
 const bars=[0,1,2].map(i=>box('Cedar completed bars '+i,-.77+i*.32,1.86,-.29,.20,.40,.22,purple));
 const seals=[0,1,2,3,4].map(i=>{const m=MeshBuilder.CreateSphere('Cedar evidence seal '+i,{diameter:.13,segments:12},scene);m.parent=root;m.position.set((i-2)*.29,1.69,.38);m.material=ivory;m.isPickable=false;return m;});
 function plate(id:string,x:number,y:number,w:number,h:number,tw:number,th:number){const texture=new DynamicTexture('Cedar '+id,{width:tw,height:th},scene,true),m=new StandardMaterial('Cedar print '+id,scene);m.diffuseTexture=texture;m.emissiveColor=Color3.White();m.disableLighting=true;m.backFaceCulling=false;const face=MeshBuilder.CreatePlane('Cedar '+id,{width:w,height:h},scene);face.parent=root;face.position.set(x,y,.35);face.material=m;return {id,texture,face};}
 const ports=[['sources','SOURCES'],['report','REPORT'],['repeat','REPEAT']].map(([id,label],i)=>{const p=plate(id,(i-1)*.86,3.09,.80,.34,512,224);p.face.actionManager=new ActionManager(scene);p.face.actionManager.registerAction(new ExecuteCodeAction(ActionManager.OnPickTrigger,()=>onAction(id)));return {...p,label};});
 const card=plate('report readout',0,2.28,2.18,.96,1024,448);card.face.isPickable=false;const strip=plate('evidence status',0,2.85,2.22,.16,1024,80);strip.face.isPickable=false;
 let state:any=freshCapstone(),signature='';
 function setState(s:any){state=s;const sig=JSON.stringify([s.section,s.week,s.outputs,s.checks,s.first,s.reviews,s.rehearsal,s.revision]);if(sig===signature)return;signature=sig;const o=s.outputs[s.week],check=s.checks[s.week],rubric=capstoneRubric(s);seals.forEach((p,i)=>p.material=s.first&&rubric[i].pass?green:ivory);bars.forEach((p,i)=>{p.scaling.y=o?(i+1)*.45:1;});
 for(const p of ports){const c=p.texture.getContext() as CanvasRenderingContext2D;c.fillStyle=p.id===s.section?'#51436a':'#eee6d6';c.fillRect(0,0,512,224);c.fillStyle=p.id===s.section?'#f5efdf':'#334338';c.textAlign='center';c.font='bold 56px sans-serif';c.fillText(p.label,256,104);c.font='30px sans-serif';c.fillText(p.id==='sources'?'CHOOSE THE INPUTS':p.id==='report'?'INSPECT THE CLAIMS':'TEST THE PROCEDURE',256,172);p.texture.update();}
 const c=card.texture.getContext() as CanvasRenderingContext2D;c.fillStyle='#334338';c.fillRect(0,0,1024,448);c.fillStyle='#eee6d6';c.textAlign='left';c.font='bold 44px sans-serif';c.fillText('CEDAR RESEARCH',52,80);c.font='34px sans-serif';c.fillText(o?o.metrics.week:'YOUR INDEPENDENT HANDOFF',52,139);c.font='bold 81px sans-serif';c.fillText(o?String(o.metrics.completed)+' DONE':'YOUR BRIEF',52,263);c.textAlign='right';c.fillText(o?o.metrics.revenue_change.toFixed(2)+'%':'YOUR CALL',972,263);c.textAlign='left';c.font='34px sans-serif';c.fillText(o?'COMPLETED ONBOARDINGS':'CONTEXT · TOOLS',52,327);c.textAlign='right';c.fillText(o?'REVENUE CHANGE':'EVIDENCE · REUSE',972,327);c.textAlign='center';c.fillStyle=check&&!check.pass?'#efb295':'#dce7ce';c.font='bold 32px sans-serif';c.fillText(o?.revision!==s.revision&&o?'EARLIER REVISION':check?check.pass?'SAVED CLAIMS CHECKED':'SAVED CLAIM MISMATCH':'WAITING FOR YOUR EVIDENCE',512,407);card.texture.update();
 const sc=strip.texture.getContext() as CanvasRenderingContext2D;sc.fillStyle=capstonePass(s)?'#37573f':'#51436a';sc.fillRect(0,0,1024,80);sc.fillStyle='#f5efdf';sc.textAlign='center';sc.font='bold 34px sans-serif';sc.fillText(s.first?`${rubric.filter(c=>c.pass).length}/5 CURRENT · ${s.first.scores.filter(Boolean).length}/5 FIRST SUBMISSION`:'A FRESH CLIENT · FIVE USEFUL HABITS',512,54);strip.texture.update();
 }
 setState(state);return {setState,setEnabled:(enabled:boolean)=>root.setEnabled(enabled),state:()=>({visible:root.isEnabled(),verified:capstonePass(state),ports:ports.map(p=>{const e=scene.getEngine(),v=scene.activeCamera!.viewport.toGlobal(e.getRenderWidth(),e.getRenderHeight());v.y=e.getRenderHeight()-v.y-v.height;const q=Vector3.Project(p.face.getAbsolutePosition(),Matrix.Identity(),scene.getTransformMatrix(),v);return {id:p.id,screen:{x:q.x*e.getRenderingCanvas()!.clientWidth/e.getRenderWidth(),y:q.y*e.getRenderingCanvas()!.clientHeight/e.getRenderHeight()}};})})};
}
