import {contextSources} from './context-lab.mjs';
import {depthResult,depthRequest} from './context-depth.mjs';
const esc=(v:unknown)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function contextDepthView(s:any,playing:boolean,paused:boolean,reduced:boolean){
 const lab:any=depthResult(s),owner=lab.result!.row.approval_owner,old=s.source==='old';
 const doc=contextSources.find(f=>f.id===s.document)!;
 const guide=s.checked?(old?'The draft contains a name. The check tells us it is the wrong name. Follow the current brief back to the field.':'Now the source, saved field and check agree. The other three CSV values stayed intact.'):s.traced?'Follow the light to approval_owner. The source choice changes this field; the existing CSV supplies the other values.':'Every source has a job. Pull out the current brief, or try the older proposal and follow its fact into the output.';
 return `<section class="depth-shell" aria-label="Inside the Context Archive"><nav class="depth-breadcrumb" aria-label="Exploration breadcrumb"><button data-action="depth-close">Context Archive</button><span>/</span><strong>Inside the evidence</strong></nav><div class="depth-scene-title"><span>EXPLORE INSIDE / 01</span><h1>Follow a fact.</h1><p>Source. Field. Proof.</p></div><aside class="depth-inspector"><header><span>THE CONTEXT ARCHIVE</span><button data-action="depth-close" aria-label="Return to station">↶ Return to station</button></header><nav class="depth-tabs" aria-label="Inspection points">${[['source','01 Source'],['output','02 Field'],['evidence','03 Proof']].map(([id,name])=>`<button data-action="depth-focus" data-value="${id}" aria-pressed="${s.focus===id}">${name}</button>`).join('')}</nav><div class="depth-content" tabindex="0" aria-label="Evidence inspector">
 <h2 tabindex="-1">${s.focus==='source'?'Which brief supplies the fact?':s.focus==='output'?'One source. One changed field.':'What makes this result trustworthy?'}</h2>
 <div class="depth-source-switch" aria-label="Choose the source"><button data-action="depth-source" data-value="brief" aria-pressed="${!old}">September brief <small>Approved · Sep 9</small></button><button data-action="depth-source" data-value="old" aria-pressed="${old}">August proposal <small>Superseded · Aug 12</small></button></div>
 <div class="depth-flow ${s.traced?'is-traced':''} ${old?'is-stale':''}"><span>${old?'AUGUST':'SEPTEMBER'}<strong>${esc(owner)}</strong></span><i aria-hidden="true">→</i><span>CSV FIELD<strong>approval_owner</strong></span></div>
 ${s.focus==='source'?`<article class="depth-document"><div>${old?'AUGUST-PROPOSAL.md':'CLIENT-BRIEF.md'}</div><p>${old?'Approval owner: <mark>Evan Cole.</mark>':'<mark>Nina Patel</mark> now approves every delivery. This replaces the approval owner in the August proposal.'}</p><small>${old?'Historical requirements. The September brief explicitly replaces this owner.':'Current approved requirements. Supplies the owner, not the entire working environment.'}</small></article><p class="depth-explanation">Choose either source, then trace its fact into the draft. The approved September brief remains the comparison standard.</p>`:''}
 ${s.focus==='output'?`<div class="depth-file-header">onboarding.csv <span>DEMONSTRATION DRAFT</span></div><dl class="depth-fields">${Object.entries(lab.result!.row).map(([k,v])=>`<div class="${k==='approval_owner'?'changed':''}"><dt>${esc(k)}</dt><dd>${esc(v)}${k==='approval_owner'?`<small>From ${old?'August proposal':'September brief'}</small>`:'<small>Preserved from existing CSV</small>'}</dd></div>`).join('')}</dl><p class="depth-explanation">A populated field can still be wrong. Compare the saved draft with the approved requirements.</p>`:''}
 ${s.focus==='evidence'?`<div class="depth-verdict ${s.checked?(old?'failed':'passed'):''}" role="status"><strong>${s.checked?(old?'MISMATCH FOUND':'FOUR FIELDS VERIFIED'):'Ready to compare'}</strong><p>${s.checked?(old?'Expected Nina Patel; the draft contains Evan Cole. The attached August proposal is superseded.':'The saved CSV matches the approved brief and preserves the client, kickoff and file-access values.'):'Read back the generated CSV and compare every field with the approved brief.'}</p></div><div class="depth-evidence-links">${[['brief','Fact · approved brief'],['sample','Existing values · CSV'],['image','Failed field · screenshot'],['agents','Format and check · AGENTS.md'],['note','Imported text · no new authority']].map(([id,name])=>`<button data-action="depth-inspect" data-value="${id}" aria-pressed="${s.document===id}">${name}</button>`).join('')}</div><details class="depth-source-text" ${s.inspected?'open':''}><summary>Read ${esc(doc.name)}</summary>${doc.image?`<img src="${doc.image}" alt="${esc(doc.body)}"/>`:`<pre>${esc(doc.body)}</pre>`}</details><details class="depth-source-text"><summary>Take this habit into Codex</summary><p>${esc(depthRequest)}</p><button data-action="depth-download">Download source trace ↓</button><a href="https://learn.chatgpt.com/docs/agent-configuration/agents-md" target="_blank" rel="noopener noreferrer">Project guidance documentation ↗</a><small>Fixture and documentation lock: September 10, 2026.</small></details>`:''}
 </div><footer class="depth-actions"><button class="button-primary" data-action="${s.traced?'depth-check':'depth-trace'}">${s.traced?'Compare saved draft':'Trace this fact'} <span>→</span></button><button data-action="depth-example">${playing?'Stop example':'Play example'}</button></footer></aside><aside class="depth-guide"><img src="/assets/codex-reference.png" alt=""/><p>${esc(guide)}</p></aside><footer class="depth-bottom"><span>Fictional Northstar demonstration · Your exercise stays intact</span><div><button data-action="depth-motion">${reduced?'Motion off':'Motion on'}</button><button data-action="depth-pause">${paused?'Resume':'Pause'}</button><button data-action="depth-reset">Reset</button><button data-action="depth-close">Back / Esc</button></div></footer></section>`;
}
