import {Scene} from '@babylonjs/core/scene';import {TransformNode} from '@babylonjs/core/Meshes/transformNode';import {MeshBuilder} from '@babylonjs/core/Meshes/meshBuilder';import {Vector3,Matrix} from '@babylonjs/core/Maths/math.vector';import {Color3} from '@babylonjs/core/Maths/math.color';import {PBRMaterial} from '@babylonjs/core/Materials/PBR/pbrMaterial';import {StandardMaterial} from '@babylonjs/core/Materials/standardMaterial';import {DynamicTexture} from '@babylonjs/core/Materials/Textures/dynamicTexture';import {ActionManager} from '@babylonjs/core/Actions/actionManager';import {ExecuteCodeAction} from '@babylonjs/core/Actions/directActions';import {freshHandoff,handoffPass} from './handoff-lab.mjs';
export function buildHandoffExhibit(scene:Scene,anchor:Vector3,onAction:(id:string)=>void){
 const root=new TransformNode('Handoff delivery dock',scene);root.position=anchor.clone();
 const mat=(name:string,color:string,metal=0)=>{const m=new PBRMaterial(name,scene);m.albedoColor=Color3.FromHexString(color);m.metallic=metal;m.roughness=.32;return m;};const ivory=mat('Handoff ceramic','#ebe5d8'),graphite=mat('Handoff graphite','#344038'),metal=mat('Handoff satin metal','#b1b5ac',.7),green=mat('Handoff checked seal','#8daf7d'),red=mat('Handoff failed seal','#b8725b');
 function box(name:string,x:number,y:number,z:number,w:number,h:number,d:number,m:PBRMaterial){const b=MeshBuilder.CreateBox(name,{width:w,height:h,depth:d},scene);b.parent=root;b.position.set(x,y,z);b.material=m;b.isPickable=false;return b;}
 box('Dock base',0,1.57,0,2.64,.14,.86,metal);box('Recovery case',-.66,1.92,0,1.12,.57,.6,graphite);box('Delivery case',.66,1.92,0,1.12,.57,.6,ivory);box('Delivery connecting rail',0,1.83,-.07,.22,.06,.13,metal);
 const seals=[box('Recovery seal',-.66,1.72,.32,.6,.07,.05,ivory),box('Delivered seal',.66,1.72,.32,.6,.07,.05,ivory)];
 const papers=Array.from({length:4},(_,i)=>box('Packaged file '+i,.66+(i-1.5)*.06,2.35+i*.06,-.07,.77,.55,.035,ivory));
 function plate(id:string,x:number,y:number,w:number,h:number,tw=512,th=224){const texture=new DynamicTexture('Handoff '+id,{width:tw,height:th},scene,true),m=new StandardMaterial('Handoff ink '+id,scene);m.diffuseTexture=texture;m.emissiveColor=Color3.White();m.disableLighting=true;m.backFaceCulling=false;const face=MeshBuilder.CreatePlane('Handoff '+id,{width:w,height:h},scene);face.parent=root;face.position.set(x,y,.35);face.material=m;return {id,texture,face};}
 const ports=[['prepare','FILES'],['delivery','DELIVERY'],['evidence','EVIDENCE']].map(([id,label],i)=>{const p=plate(id,(i-1)*.86,3.09,.8,.34);p.face.actionManager=new ActionManager(scene);p.face.actionManager.registerAction(new ExecuteCodeAction(ActionManager.OnPickTrigger,()=>onAction(id)));return {...p,label};});
 const cards=[plate('recovery card',-.66,2.30,1.06,.91,512,440),plate('delivery card',.66,2.30,1.06,.91,512,440)];cards.forEach(p=>p.face.isPickable=false);const status=plate('handoff status',0,2.84,2.24,.16,1024,80);status.face.isPickable=false;
 let s:any=freshHandoff(),sig='';
 function setState(next:any){s=next;const key=JSON.stringify([s.section,s.delivered,s.deliveredCheck,s.recovery,s.package,s.localCheck,s.revision]);if(key===sig)return;sig=key;
  seals[0].material=s.recovery?green:ivory;seals[1].material=s.deliveredCheck?.id===s.delivered.id?s.deliveredCheck.pass?green:red:ivory;papers.forEach((p,i)=>p.isVisible=i<Object.keys(s.delivered.files).length);
  for(const p of ports){const c=p.texture.getContext() as CanvasRenderingContext2D;c.fillStyle=p.id===s.section?'#51436a':'#ebe6db';c.fillRect(0,0,512,224);c.fillStyle=p.id===s.section?'#f4f0e6':'#343f37';c.textAlign='center';c.font='bold 57px sans-serif';c.fillText(p.label,256,100);c.font='29px sans-serif';c.fillText(p.id==='prepare'?'BUILD THE PACKAGE':p.id==='delivery'?'CHECK THE REAL COPY':'PROVE THE HANDOFF',256,168);p.texture.update();}
  cards.forEach((p,i)=>{const c=p.texture.getContext() as CanvasRenderingContext2D;c.fillStyle=i?'#e9e4d9':'#344038';c.fillRect(0,0,512,440);c.fillStyle=i?'#344038':'#eee8da';c.font='bold 43px sans-serif';c.textAlign='center';c.fillText(i?'DELIVERED':'RECOVERY',256,83);c.font='bold 57px sans-serif';c.fillText(i?String(Object.keys(s.delivered.files).length)+' FILES':s.recovery?'PRESERVED':'KEEP FIRST',256,199);c.font='33px sans-serif';c.fillText(i?(s.deliveredCheck?.id===s.delivered.id?s.deliveredCheck.pass?'CHECKED':'FAILED':'NEEDS CHECK'):(s.rollbackVerified?'RESTORE VERIFIED':s.recovery?'WORKING COPY':'VERIFY + PRESERVE'),256,288);c.font='30px sans-serif';c.fillText(i?'RELEASE '+s.delivered.id:'SEPARATE FILES',256,371);p.texture.update();});
  const c=status.texture.getContext() as CanvasRenderingContext2D;c.fillStyle=handoffPass(s)?'#365a3d':'#344038';c.fillRect(0,0,1024,80);c.fillStyle='#eee8da';c.textAlign='center';c.font='bold 35px sans-serif';c.fillText(handoffPass(s)?'REPAIRED · DELIVERED · RECOVERABLE':'LOCAL FILES → PACKAGE → DELIVERY',512,55);status.texture.update();
 }
 setState(s);return {setState,setEnabled:(enabled:boolean)=>root.setEnabled(enabled),update:(_dt:number,_reduced:boolean)=>{},state:()=>({verified:handoffPass(s),deliveredId:s.delivered.id,preserved:!!s.recovery,ports:ports.map(p=>{const e=scene.getEngine(),v=scene.activeCamera!.viewport.toGlobal(e.getRenderWidth(),e.getRenderHeight());v.y=e.getRenderHeight()-v.y-v.height;const q=Vector3.Project(p.face.getAbsolutePosition(),Matrix.Identity(),scene.getTransformMatrix(),v);return {id:p.id,screen:{x:q.x*e.getRenderingCanvas()!.clientWidth/e.getRenderWidth(),y:q.y*e.getRenderingCanvas()!.clientHeight/e.getRenderHeight()}};})})};
}
