export const handoffBrand='<svg xmlns="http://www.w3.org/2000/svg" width="240" height="64" viewBox="0 0 240 64"><rect width="240" height="64" rx="10" fill="#254d3b"/><path d="M31 10 36 26 53 31 36 36 31 53 26 36 10 31 26 26Z" fill="#efe6cc"/><text x="67" y="40" fill="#fff8e8" font-family="sans-serif" font-size="23">Northstar</text></svg>';
export const handoffCSV='client,kickoff,files,approval_owner\nNorthstar Studio,scheduled,requested,Nina Patel\n';
export function deliveryPage(mode='relative'){return `<!doctype html>\n<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Northstar — kickoff guide</title><style>body{font:16px/1.5 system-ui,sans-serif;background:#f1eee3;color:#243f30;margin:0;padding:28px}main{max-width:540px;margin:auto}img{width:210px;max-width:100%;height:auto}h1{font-size:28px;line-height:1.15}dl{display:grid;grid-template-columns:1fr 1fr;gap:12px}dd{margin:0;font-weight:600}a{color:#244f3c}small{display:block;margin-top:25px}</style></head><body><main>${mode==='hide'?'<!-- Brand image removed -->':`<img src="${mode==='absolute'?'/assets/brand.svg':'./assets/brand.svg'}" alt="Northstar brand mark">`}<h1>Your kickoff guide.</h1><p>Northstar Studio</p><dl><dt>Kickoff</dt><dd>Scheduled</dd><dt>File access</dt><dd>Requested</dd><dt>Approval owner</dt><dd data-owner="Nina Patel">Nina Patel</dd></dl><p><a href="./onboarding.csv" download>Download the onboarding checklist</a></p><small>Fictional training data. No client account or email connection.</small></main></body></html>\n`;}
export const usefulDeliveryNotes='# Use the Northstar guide\n\nServe the parent directory with `python3 -m http.server 8000`, then open http://127.0.0.1:8000/northstar/. Keep index.html, assets/brand.svg and onboarding.csv together. Verify the brand image, approval owner Nina Patel and CSV download from that exact route.\n\nRecovery: the separate recovery/northstar folder contains the earlier working release. Serve recovery as the root or restore its northstar folder, then check the same route again. Never replace the only working recovery copy with an unverified candidate.\n\nKnown limits: fictional static data; no authentication, email delivery or live source sync. The rehearsal checks file references and fixture content. Real-device, performance and production-host checks still need to be performed for any real deployment.\n';
export const packageItems={page:'index.html',brand:'assets/brand.svg',data:'onboarding.csv',guide:'README.md'};
export function candidateFiles(s){return {'index.html':deliveryPage(s.mode),'assets/brand.svg':handoffBrand,'onboarding.csv':handoffCSV,'README.md':s.notes==='useful'?usefulDeliveryNotes:'Done! Everything is perfect.\n'};}
const recoveryFiles=()=>({'index.html':deliveryPage('relative'),'assets/brand.svg':handoffBrand,'onboarding.csv':handoffCSV,'README.md':usefulDeliveryNotes});
export const freshHandoff=()=>({section:'delivery',surface:'delivered',revision:2,mode:'absolute',notes:'claim',selected:['page','brand','data'],package:null,localCheck:null,delivered:{id:1,kind:'original',revision:1,files:recoveryFiles()},deliveredCheck:null,recovery:null,nextId:2,failureSeen:false,rollbackVerified:false,actions:[],events:[],message:'A working guide is already delivered. Check that copy and preserve it before staging the candidate. Local checks alone cannot prove a delivered package works.'});
const note=(s,m)=>{s.message=m;s.events.push(m);s.events=s.events.slice(-60);};
export function analyzeDelivery(files,surface){const base=surface==='local'?'https://local.invalid/':'https://delivery.invalid/northstar/';const index=files['index.html']??'',image=index.match(/<img\s+src="([^"]+)"/),link=index.match(/<a\s+href="([^"]+)"/);const requests=[];
 const read=reference=>{if(!reference)return null;const url=new URL(reference,base),prefix=surface==='local'?'/':'/northstar/',path=url.pathname.startsWith(prefix)?decodeURIComponent(url.pathname.slice(prefix.length)):null;const found=path!==null&&Object.hasOwn(files,path);requests.push({url:url.pathname,file:path,status:found?200:404});return found?files[path]:null;};
 const svg=read(image?.[1]),csv=read(link?.[1]);
 const checks=[{name:'Page and approval owner',pass:!!index&&index.includes('data-owner="Nina Patel"')},{name:'Brand image resolves from this route',pass:!!image&&svg===handoffBrand},{name:'CSV download resolves with the approved source values',pass:csv===handoffCSV}];return {surface,base,index,requests,checks,pass:checks.every(c=>c.pass),image:svg===handoffBrand,download:csv===handoffCSV};}
export const deliveryCheckLabel=c=>c.pass?c.name:({'Page and approval owner':'Page missing or approval owner does not match the source','Brand image resolves from this route':'Brand image missing from this route','CSV download resolves with the approved source values':'CSV missing or its values do not match the source'}[c.name]??c.name);
export function previewDelivery(s){const files=s.surface==='local'?candidateFiles(s):s.delivered.files,a=analyzeDelivery(files,s.surface);if(!a.index)return '<!doctype html><html><body><h1>Page missing</h1><p>index.html was not included in this package.</p></body></html>';return a.index.replace(/<img\s+src="[^"]+"[^>]*>/,a.image?handoffBrand:'<div role="img" aria-label="Brand image missing" style="padding:20px;border:2px dashed #a34b36;color:#893626">Brand image missing</div>').replace(/<a\s+href="[^"]+"[^>]*>[^<]*<\/a>/,a.download?'<strong>onboarding.csv resolves ✓</strong>':'<strong style="color:#893626">onboarding.csv missing</strong>');}
const names=['surface','check','preserve','select','notes','repair','pack','deploy','rollback'];
export function handoffAction(input,action,value){if(action==='restart')return freshHandoff();const s=structuredClone(input);if(action==='section'&&['prepare','delivery','evidence'].includes(value)){s.section=value;return s;}if(!names.includes(action))return s;
 if(action==='surface'&&!['local','delivered'].includes(value))return s;if(action==='select'&&!Object.hasOwn(packageItems,value))return s;if(action==='notes'&&!['claim','useful'].includes(value))return s;if(action==='repair'&&!['absolute','relative','hide'].includes(value))return s;
 if(s.actions.length>=140){s.message='This rehearsal has reached its history limit. Restart to try a fresh delivery sequence.';return s;}s.actions.push({action,...(value===undefined?{}:{value})});
 if(action==='surface'){s.surface=value;note(s,value==='local'?'Previewing the complete local workspace at /. Its asset path can work here and fail under the delivery route.':'Previewing only the staged files under /northstar/. This is the copy the recipient would receive.');}
 if(action==='check'){const a=analyzeDelivery(s.surface==='local'?candidateFiles(s):s.delivered.files,s.surface),result={id:s.surface==='local'?s.revision:s.delivered.id,pass:a.pass,checks:a.checks,requests:a.requests};if(s.surface==='local')s.localCheck=result;else{s.deliveredCheck=result;if(!a.pass)s.failureSeen=true;if(a.pass&&s.delivered.kind==='rollback'&&s.delivered.fromFailed)s.rollbackVerified=true;}note(s,(s.surface==='local'?'Local':'Delivered')+' check '+(a.pass?'passed.':'failed: '+a.checks.filter(c=>!c.pass).map(deliveryCheckLabel).join(';')+'.')+(s.surface==='local'?' The delivery copy still needs its own check.':s.delivered.kind==='rollback'&&a.pass?' The preserved version is working again.':''));}
 if(action==='preserve'){if(!s.deliveredCheck?.pass||s.deliveredCheck.id!==s.delivered.id){note(s,'Check the current delivered copy successfully before preserving it.');return s;}if(s.recovery){note(s,'The earlier working recovery copy is already preserved. It will not be overwritten.');return s;}s.recovery=structuredClone(s.delivered);note(s,'Preserved the verified delivered files as the recovery copy.');}
 if(action==='select'){s.selected=s.selected.includes(value)?s.selected.filter(x=>x!==value):[...s.selected,value];s.package=null;note(s,'Package selection changed. Rebuild it to update the actual staged files.');}
 if(action==='notes'){if(s.notes!==value){s.notes=value;s.revision++;s.package=null;s.localCheck=null;}note(s,value==='useful'?'Prepared use instructions, route-specific verification, recovery steps and honest limits.':'The note only claims completion. It does not tell the recipient how to use or recover the files.');}
 if(action==='repair'){if(s.mode!==value){s.mode=value;s.revision++;s.package=null;s.localCheck=null;}note(s,value==='relative'?'Changed the image reference to ./assets/brand.svg. Recheck locally, rebuild and stage it before testing the delivery.':value==='hide'?'The image was removed. That hides the symptom but fails the required brand presentation.':'Restored the original /assets/brand.svg reference. It assumes the site lives at the server root.');}
 if(action==='pack'){const all=candidateFiles(s);s.package={revision:s.revision,files:Object.fromEntries(s.selected.map(id=>[packageItems[id],all[packageItems[id]]]))};note(s,'Built a package containing '+Object.keys(s.package.files).join(', ')+'. It is separate from both the workspace and current delivery.');}
 if(action==='deploy'){if(!s.recovery){note(s,'Preserve a verified recovery copy before staging a new release.');return s;}if(!s.package||s.package.revision!==s.revision){note(s,'Build the current package before staging it.');return s;}s.delivered={id:s.nextId++,kind:'candidate',revision:s.revision,files:structuredClone(s.package.files)};s.deliveredCheck=null;s.surface='delivered';note(s,'Candidate staged in the delivery rehearsal. Check this copy from /northstar/ before trusting it.');}
 if(action==='rollback'){if(!s.recovery){note(s,'No recovery copy has been preserved.');return s;}const fromFailed=!!s.deliveredCheck&&!s.deliveredCheck.pass&&s.deliveredCheck.id===s.delivered.id;s.delivered={id:s.nextId++,kind:'rollback',revision:s.recovery.revision,files:structuredClone(s.recovery.files),fromFailed};s.deliveredCheck=null;s.surface='delivered';note(s,'Restored the preserved files in the rehearsal. Verify the restored delivery before calling recovery complete.');}
 return s;}
export function handoffChecks(s){return [
 {name:'Earlier working files preserved separately',pass:!!s.recovery&&analyzeDelivery(s.recovery.files,'delivered').pass},
 {name:'Delivery failure observed and recovery verified',pass:s.failureSeen&&s.rollbackVerified},
 {name:'Current local repair passes without removing the brand',pass:s.mode==='relative'&&s.localCheck?.id===s.revision&&s.localCheck.pass},
 {name:'Package contains the page, brand, CSV and useful instructions',pass:!!s.package&&s.package.revision===s.revision&&Object.values(packageItems).every(p=>Object.hasOwn(s.package.files,p))&&s.package.files['README.md']===usefulDeliveryNotes},
 {name:'Current repaired package staged and checked at the delivery route',pass:s.delivered.kind==='candidate'&&s.delivered.revision===s.revision&&s.deliveredCheck?.id===s.delivered.id&&s.deliveredCheck.pass&&!!s.package&&JSON.stringify(s.delivered.files)===JSON.stringify(s.package.files)}
 ];}
export const handoffPass=s=>!!s&&handoffChecks(s).every(c=>c.pass===true);
export const handoffReceipt=s=>handoffPass(s)?{version:1,simulation:true,actions:s.actions,delivered:s.delivered,recovery:s.recovery,localCheck:s.localCheck,deliveredCheck:s.deliveredCheck,checks:handoffChecks(s)}:null;
export function normalizeHandoffReceipt(r){if(r?.version!==1||r.simulation!==true||!Array.isArray(r.actions)||r.actions.length>140)return null;let s=freshHandoff();for(const a of r.actions){if(!a||!names.includes(a.action)||Object.keys(a).some(k=>!['action','value'].includes(k))||(a.value!==undefined&&(typeof a.value!=='string'||a.value.length>30)))return null;s=handoffAction(s,a.action,a.value);}const expected=handoffReceipt(s);return expected&&JSON.stringify(expected)===JSON.stringify(r)?expected:null;}
export function handoffFiles(r){return {...Object.fromEntries(Object.entries(r.delivered.files).map(([p,text])=>['handoff-dock/site/northstar/'+p,text])),...Object.fromEntries(Object.entries(r.recovery.files).map(([p,text])=>['handoff-dock/recovery/northstar/'+p,text])),'handoff-dock/rehearsal.json':JSON.stringify(r,null,2)+'\n','handoff-dock/RELEASE-NOTES.md':`# Northstar delivery rehearsal\n\nThe current package uses ./assets/brand.svg and includes its CSV, brand asset and use instructions. The original root-absolute asset path worked in the complete local workspace but failed at the mounted /northstar/ delivery route. The earlier working files were restored and checked before staging the repaired candidate.\n\n## Run the actual exported page\nFrom this folder, run \`python3 -m http.server 8000 --directory site\`. Open http://127.0.0.1:8000/northstar/ and inspect the image and CSV download. Stop the server, then use \`--directory recovery\` to inspect the preserved version at the same path.\n\n## Evidence and limits\n${r.checks.map(c=>'- '+c.name+': observed in rehearsal').join('\n')}\n\nThe game models file routing and checks fixed content. Its iframe replaces file requests with known embedded assets and marks missing references; it is not a real remote deployment or HTTP test. The exported package contains actual HTML, SVG and CSV for independent browser testing. No site was published by the exercise. Here.now and other hosts have their own routing rules; this example is not a claim about their default mount paths.\n\nThis lesson uses “handoff” to mean delivery to a recipient, distinct from Codex's Local/Worktree handoff command. The simulation does not move a real Codex task. Real-device, performance and production-host validation remain separate.\n\nOfficial browser-review guidance checked September 10, 2026: https://learn.chatgpt.com/docs/browser\n`};}
