// Worked examples explain the exercise without manufacturing checked artifacts.
const solutions={
 task:['Title: Review the Northstar onboarding checklist.','Brief: Review the checklist, identify missing approval steps, and verify the saved result against the approved client brief.','Choose medium or high effort, enable Pin task, then create the task.'],
 context:['Inspect and attach the current September brief, onboarding CSV, error screenshot and AGENTS.md. Leave out the superseded proposal and unrelated note.','Use the current client requirements. Repair approval_owner to Nina Patel, preserving the CSV’s other values.','Build the context pack and saved draft, then run the comparison against the approved brief.'],
 models:['Label job: replace Clinet with Client. Run and check the same edit at two different setups, then keep a passing route.','Billing job: run and check the original calculation to reproduce the defect. Inspect all three files. Apply the discount before tax, run and check again, then keep the route.','Sheet job: try the unavailable read first. Connect the source, choose September 10, then run, check and keep the route.'],
 permissions:['Choose Workspace + Northstar access, or Ask when needed and allow the one source read. Read the approved source successfully.','Connect the training mail app separately. Leave unused command network access off.','Create the requested draft and verify its contents and unsent status. Resolve any pending requests; do not send it.'],
 branch:['Run A and B in the shared checkout to observe the overwrite.','Create separate worktrees. Run and check both attempts, then compare the actual changes.','Integrate attempt A, which preserves every required field, and verify the local result after integration.'],
 steering:['Send the status request through Steer and advance one work step.','While the checklist is still running, steer it to French. Queue the welcome email to use the latest checked checklist.','Advance until the active run and queue finish. Inspect the French checklist and the saved, unsent welcome draft. Restart the rehearsal if the correction arrived too late.'],
 review:['Run acceptance checks to reproduce the regression.','Flag the lines that overwrite approvers and clear file access. Keep the requested heading correction.','Apply the focused repair, rerun the three acceptance cases, and inspect the final diff before keeping it.'],
 tools:['Inspect Source Kit, install it, connect it to Training briefs and read the project guidance. Load the first example skill.','Read Harbor’s brief, run the example and verify: its hard-coded Nina Patel owner fails against Amir Chen.','Load the reusable skill. Run and verify Harbor again, then read, run and verify Northstar. Each output must preserve its own client’s values.'],
 browser:['Enter Nina Patel and save. Reload to reproduce the disappearing record.','Apply the persistence repair. Enter Nina Patel again and save.','Reload again: the saved record must still contain Nina Patel. Then check the exercise.'],
 automation:['Use the durable prompt, weekdays at 9 a.m. in America/Toronto, notifications for meaningful changes, and a local host that is available. Test and enable it.','Advance five minutes for an unchanged run. Set the source to missing approval and advance through the next weekday run: expect one alert, then quiet repeats.','Set the source unavailable and advance to a due run. Recover the approved source and run again.','Turn the host off across a due run, then restore it and advance to the next due run. Keep the schedule after observing the failure and recovery evidence.'],
 handoff:['Check the current delivered page and preserve the working recovery copy.','Check the local candidate, build the package, stage it and check the delivery. The root-absolute image path fails under the delivery route.','Restore the recovery copy and check it.','In Files, choose the relative image path, useful release notes and README. Check locally, rebuild, stage and check the repaired delivery.'],
 capstone:['Define a Cedar weekly reporting task for September 7, 2026. Choose report + CSV and the completed, completion-rate and revenue-growth metrics. Include a concrete saved-result check in the task summary.','Use the client brief, current actuals and project instructions. Enable data reading and file writing with Training scope. Leave unrelated and private sources out.','Use the previous-period denominator: (current revenue − previous revenue) / previous revenue. The first revenue change is 8%; the next is 5%.','For both the first and next reporting periods, run the procedure, open the saved files and run the independent check.','Schedule Mondays at 9 a.m. in America/Toronto, notify on changes, preserve the last good files on source failure, and require the local host to be available. Rehearse, then submit the handoff.'],
};
export function workedAnswer(step){
 if(step.kind==='select'||step.kind==='order')return {ordered:step.kind==='order',items:step.answer.map(id=>{const option=step.options.find(o=>o.id===id);return option?`${option.label} — ${option.detail}`:id;}),explanation:step.success};
 return {ordered:true,items:solutions[step.kind]??[step.hint],explanation:step.success};
}
