import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const root=path.resolve('..'),stage=path.join(root,'evidence/production/architecture-textures-v1');const read=async p=>JSON.parse(await fs.readFile(p,'utf8'));
async function runFrom(log,role){const events=(await fs.readFile(path.join(stage,log),'utf8')).trim().split('\n').map(l=>JSON.parse(l));const event=events.find(e=>e.type==='completed');assert(event?.data.runPath);const p=event.data.runPath,r=await read(path.join(p,'traversal.json'));assert(r.pass);return {role,runId:event.data.run.runId,runPath:p,buildId:r.buildId,quality:r.quality,summary:r.summary,profile:r.profile,browser:r.browser,graphics:r.graphics,viewport:r.viewport,dpr:r.dpr,inputs:r.inputs};}
const baselinePath=path.resolve('assets/generated/.game-dev/runs/run_1789048657891_d27c12c4f9ae4c79ae16612042a20c2a'),base=await read(path.join(baselinePath,'traversal.json'));
const balanced=await runFrom('final-balanced.jsonl','final-balanced'),high=await runFrom('final-high.jsonl','final-high');assert.equal(balanced.buildId,high.buildId);for(const key of ['browser','quality','dpr'])assert.deepEqual(balanced[key],base[key]);assert.deepEqual(balanced.viewport,base.viewport);assert.deepEqual(balanced.graphics,base.graphics);assert.deepEqual(balanced.profile,base.profile);
for(const name of ['final-balanced-verify.json','final-high-verify.json'])assert((await read(path.join(stage,name))).ok);
for(const name of ['browser-recovery/report.json','context-settled/report.json','journey-recovery/report.json','views-recovery/comparison.json'])assert((await read(path.join(stage,name))).pass);
const goal=await read('.game-dev/goals/architecture-gpu-textures.json');assert.equal(goal.state.status,'met');assert.equal(goal.state.iterations.length,1);
for(const f of balanced.inputs){const b=await fs.readFile(f.path);assert.equal(b.length,f.bytes);assert.equal(crypto.createHash('sha256').update(b).digest('hex'),f.sha256);}
const allocation={baselineBalanced:base.summary.maxTextureEstimateBytes,finalBalanced:balanced.summary.maxTextureEstimateBytes,finalHigh:high.summary.maxTextureEstimateBytes,savedBalanced:base.summary.maxTextureEstimateBytes-balanced.summary.maxTextureEstimateBytes};
const artifact={date:new Date().toISOString(),goalStatus:goal.state.status,evidenceVerified:true,candidateBuildId:balanced.buildId,allocation,runs:[{role:'baseline',runId:path.basename(baselinePath),runPath:baselinePath},{role:'pre-recovery-diagnostic',runId:'run_1789050100297_e1d4b98a4a744eb88d3492923cfe6877',runPath:path.resolve('assets/generated/.game-dev/runs/run_1789050100297_e1d4b98a4a744eb88d3492923cfe6877')},balanced,high],checks:{unit:76,allocationUnit:3,journey:37,browserActualCases:9,browserInapplicableFixtures:3,contextRestoration:'Chrome actual loss/restoration with resource and state checks',finalFixedViews:10},scope:'One final warm traversal per quality. ASTC observed; BC7 and physical devices not exercised. Estimated allocations, not native VRAM or GPU timing. Pre-recovery run is diagnostic and was never goal-evaluated.',regressionsAndOpenGates:['Startup currently downloads originals plus 11.91 MB compressed maps; delivery budgets remain open.','Unsupported compression devices retain original texture memory costs.','Geometry/draw budgets, automatic quality advice, repeated performance trials and audio-enabled soak remain open.','Listening, full art/device/human review, source lock and hosted release acceptance remain open.'],fullReleaseAccepted:false};await fs.writeFile(path.join(stage,'assessment.json'),JSON.stringify(artifact,null,2)+'\n');console.log(JSON.stringify({goalStatus:artifact.goalStatus,allocation,buildId:balanced.buildId,fullReleaseAccepted:false}));
