import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {stripTypeScriptTypes} from 'node:module';
import {NullEngine} from '@babylonjs/core/Engines/nullEngine.js';import {Scene} from '@babylonjs/core/scene.js';import {MeshBuilder} from '@babylonjs/core/Meshes/meshBuilder.js';import {TransformNode} from '@babylonjs/core/Meshes/transformNode.js';import {StandardMaterial} from '@babylonjs/core/Materials/standardMaterial.js';import {Skeleton} from '@babylonjs/core/Bones/skeleton.js';import {ActionManager} from '@babylonjs/core/Actions/actionManager.js';
let source=await fs.readFile(new URL('../../src/skinned-guide-batch.ts',import.meta.url),'utf8');source=source.replace(/from '(@babylonjs\/[^']+)'/g,(_,id)=>`from '${import.meta.resolve(id+'.js')}'`);const {batchSkinnedGuide}=await import('data:text/javascript;base64,'+Buffer.from(stripTypeScriptTypes(source)).toString('base64'));
function fixture(){const engine=new NullEngine(),scene=new Scene(engine),root=new TransformNode('skin-root',scene),skeleton=new Skeleton('rig','rig',scene),material=new StandardMaterial('porcelain',scene);root.scaling.z=-1;const part=(name,offset=0)=>{const m=MeshBuilder.CreateBox(name,{size:1},scene);m.parent=root;m.material=material;m.skeleton=skeleton;const positions=m.getVerticesData('position');m.setVerticesData('position',positions.map((x,i)=>i%3===0?x+offset:x));const n=m.getTotalVertices();m.setVerticesData('matricesIndices',Array.from({length:n*4},(_,i)=>i%4===0?1:0));m.setVerticesData('matricesWeights',Array.from({length:n*4},(_,i)=>i%4===0?.75:i%4===1?.25:0));return m;};return {engine,scene,root,skeleton,material,part,close:()=>{scene.dispose();engine.dispose();}};}
test('merged skin and normal streams retain exact values, bind transform, material and ownership',()=>{const f=fixture();try{
 const a=f.part('left',-2),b=f.part('right',2);b.removeVerticesData('uv');const original=[a,b],all=[...original];const kinds=['position','normal','matricesIndices','matricesWeights'];const expected=Object.fromEntries(kinds.map(k=>[k,original.flatMap(m=>Array.from(m.getVerticesData(k)))]));const indices=[...a.getIndices(),...b.getIndices().map(i=>i+a.getTotalVertices())];const batch=batchSkinnedGuide(f.scene,all),mesh=all[2];assert.equal(batch.state().drawsSavedPerPass,1);assert.equal(mesh.skeleton,f.skeleton);assert.equal(mesh.material,f.material);assert.equal(mesh.parent,f.root);assert.deepEqual(Array.from(mesh.getPoseMatrix().m),Array.from(a.getPoseMatrix().m));assert(a.layerMask===0&&b.layerMask===0&&mesh.layerMask!==0);
 for(const k of kinds)assert.deepEqual(Array.from(mesh.getVerticesData(k)),expected[k]);assert.deepEqual(Array.from(mesh.getIndices()),indices);assert.deepEqual(Array.from(mesh.getVerticesData('uv')).slice(a.getTotalVertices()*2),Array(b.getTotalVertices()*2).fill(0));assert.equal(batch.state().batches[0].triangles,batch.state().batches[0].sourceTriangles);
 // The public projection wrapper expands batches back to the original exact bounds sources.
 let projected;const light={setShadowProjectionMatrix:(matrix,view,list)=>{projected=list;}},map={renderList:[a,b,mesh]};const originalProjection=light.setShadowProjectionMatrix;const priorWrapper=(...args)=>originalProjection(...args);light.setShadowProjectionMatrix=priorWrapper;f.scene.onDisposeObservable.addOnce(()=>{if(light.setShadowProjectionMatrix===priorWrapper)light.setShadowProjectionMatrix=originalProjection;});batch.attachShadows({getShadowMap:()=>map,getLight:()=>light});assert.deepEqual(map.renderList,[mesh]);light.setShadowProjectionMatrix(null,null,map.renderList);assert.deepEqual(projected,[a,b]);f.scene.dispose();assert.equal(light.setShadowProjectionMatrix,originalProjection);
}finally{f.close();}});
test('LOD geometry replacement refreshes skin buffers without replacing batch identities or allocating new materials',()=>{const f=fixture();try{
 const a=f.part('left'),b=f.part('right'),all=[a,b];const batches=batchSkinnedGuide(f.scene,all),mesh=all[2],materialCount=f.scene.materials.length,batchGeometry=mesh.geometry;const replacement=a.geometry.copy('new tier');replacement.applyToMesh(a);a.setVerticesData('position',a.getVerticesData('position').map(v=>v*.8));batches.refresh();assert.equal(all[2],mesh);assert.equal(mesh.geometry,batchGeometry);assert.equal(f.scene.materials.length,materialCount);assert.deepEqual(Array.from(mesh.getVerticesData('position')).slice(0,a.getTotalVertices()*3),Array.from(a.getVerticesData('position')));assert.equal(batches.state().batches[0].refreshes,2);batches.refresh();assert.equal(batches.state().batches[0].refreshes,2);
}finally{f.close();}});
test('mesh animation, actions, incompatible parents and local transforms stay on the original path',()=>{const f=fixture();try{
 const a=f.part('plain'),b=f.part('action'),c=f.part('moving'),d=f.part('other root'),e=f.part('translated');b.actionManager=new ActionManager(f.scene);f.scene.animationGroups.push({targetedAnimations:[{target:c}],dispose(){}});d.parent=new TransformNode('other',f.scene);e.position.y=1;const all=[a,b,c,d,e],batch=batchSkinnedGuide(f.scene,all);assert.equal(all.length,5);assert.equal(batch.state().batches.length,0);assert(all.every(m=>m.layerMask!==0));f.scene.animationGroups.length=0;
}finally{f.close();}});
test('missing skin streams and unavailable large indices keep original geometry',()=>{const f=fixture();try{
 const a=f.part('missing'),b=f.part('valid');a.removeVerticesData('matricesWeights');assert.equal(batchSkinnedGuide(f.scene,[a,b]).state().batches.length,0);
 f.engine.getCaps().uintIndices=false;for(const m of [a,b]){m.setVerticesData('position',new Float32Array(40000*3));m.setVerticesData('normal',new Float32Array(40000*3));m.setVerticesData('uv',new Float32Array(40000*2));m.setVerticesData('matricesIndices',new Float32Array(40000*4));m.setVerticesData('matricesWeights',new Float32Array(40000*4));}const all=[a,b];assert.equal(batchSkinnedGuide(f.scene,all).state().batches.length,0);assert(all.every(m=>m.layerMask!==0));
}finally{f.close();}});
