import {chromium,firefox,webkit} from 'playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
import {contextFlow} from '../context-flow.mjs';import {modelFlow} from '../model-flow.mjs';import {permissionFlow} from '../permission-flow.mjs';import {reviewFlow} from '../review-flow.mjs';import {steeringFlow} from '../steering-flow.mjs';import {toolsFlow} from '../tools-flow.mjs';
const out='../evidence/production/static-parts-v1',rows=[];
for(const [name,type] of Object.entries({chrome:chromium,firefox,webkit})){
 const b=await type.launch({headless:true,...(name==='chrome'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{})}),p=await b.newPage({viewport:{width:1440,height:900}}),row={name,pass:false,errors:[],checks:[]};rows.push(row);p.on('pageerror',e=>row.errors.push(e.message));
 const state=()=>p.evaluate(()=>window.__insideCodex.state());const settled=()=>p.waitForFunction(()=>{const w=window.__insideCodex.state().world;return w.ready&&w.transition===0;});
 const jump=async i=>{await p.getByRole('button',{name:'The map',exact:true}).click();await p.locator(`.map-card[data-index="${i}"]`).click();await settled();};
 try{
  await p.goto('http://127.0.0.1:43211/?renderAudit');await p.waitForFunction(()=>window.__insideCodex?.state().world?.ready);assert((await state()).world.renderAudit.meshes.some(m=>m.name.startsWith('Batch:')));
  await p.getByRole('button',{name:'Step inside'}).click();await settled();const port=(await state()).world.harness.ports.find(p=>p.id==='context');await p.locator('#world').click({position:port.screen});assert((await state()).selected.includes('context'));await p.locator('[data-action="choice"][data-value="tools"]').click();await p.locator('[data-action="choice"][data-value="verify"]').click();await p.locator('[data-action="submit"]').click();assert((await state()).world.harness.assembled);row.checks.push('Harness click and shared circuit transition');
  for(const [i,flow,key] of [[1,contextFlow,'context'],[2,modelFlow,'models'],[3,permissionFlow,'permissions'],[6,steeringFlow,'steering'],[7,reviewFlow,'review'],[8,toolsFlow,'tools']]){
   await jump(i);await flow(p);assert((await state()).world[key].verified,`${key} must remain verified`);await p.locator('[data-action="submit"]').click();assert.equal((await state()).feedback,'correct');row.checks.push(key+' complete visible-control flow and saved result');await p.screenshot({path:`${out}/${name}-${key}.png`});
  }
  await jump(5);await p.locator('[data-action="choice"][data-value="fork"]').click();await p.locator('[data-action="submit"]').click();await p.locator('[data-action="next"]').click();await p.locator('[data-action="branch-apply"][data-value="a"]').click();await p.locator('[data-action="branch-apply"][data-value="b"]').click();await p.locator('[data-action="branch-isolate"]').click();await p.waitForTimeout(500);assert.equal((await state()).world.branches.mode,'worktrees');assert((await state()).world.branches.cartridges.every(c=>Math.abs(c.x)>.4));row.checks.push('Branch cartridges still move independently');
  await p.getByRole('button',{name:'Settings',exact:true}).click();for(const q of ['balanced','high']){await p.locator('#quality').selectOption(q);await p.waitForFunction(q=>{const w=window.__insideCodex.state().world;return w.mascotDetail.active===q&&w.architecture.detail.active===q;},q);}await p.getByRole('button',{name:'Close dialog',exact:true}).click();
  const counts=[];for(let i=0;i<3;i++){await jump(11);await p.waitForTimeout(1000);await jump(3);await p.waitForTimeout(1000);const s=await state();assert.equal(s.world.permissions.verified,false);assert.equal(s.world.permissions.sourceLoaded,false);assert.equal(s.progress.workspace.permissionReview.draft.status,'DRAFT');const n=s.permissionLab.events.length;await p.locator('#world').click({position:s.world.permissions.ports.find(x=>x.id==='read').screen});assert.equal((await state()).permissionLab.events.length,n+1);assert(s.world.renderAudit.meshes.some(m=>m.name.startsWith('Batch: Permission frame')));counts.push({meshes:s.world.meshes,textures:s.world.renderAudit.textureStorageBytes});}
  assert.deepEqual(counts[2],counts[1]);row.counts=counts;row.checks.push('Quality round trip and residency reconstruction preserve saved results, restart practice, restore picking and settle at stable counts');assert.deepEqual(row.errors,[]);row.pass=true;
 }catch(error){row.error=String(error);row.state=await state().catch(()=>null);await p.screenshot({path:`${out}/${name}-failure.png`}).catch(()=>{});throw error;}
 finally{await b.close();await fs.writeFile(`${out}/browser.json`,JSON.stringify({pass:rows.length===3&&rows.every(r=>r.pass),rows},null,2));}
}
console.log('Three engines: batched exhibits preserve interaction, motion, quality changes and residency');
