import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
const stage='../evidence/production/static-shadow-v1',read=async p=>JSON.parse(await fs.readFile(p,'utf8'));
async function run(role,type){const lines=(await fs.readFile(`${stage}/${role}.jsonl`,'utf8')).trim().split('\n').map(JSON.parse),e=lines.find(e=>e.type==='completed');assert(e?.data?.runPath);assert((await read(`${stage}/${role}-verify.json`)).ok);return {role,id:e.data.run.runId,path:e.data.runPath,data:await read(path.join(e.data.runPath,type+'.json'))};}
const baseline=await run('baseline','traversal'),candidate=await run('candidate-high','traversal'),preGuard=await run('qualified-balanced','traversal'),high=await run('final-high','traversal'),balanced=await run('final-balanced','traversal'),sh=await run('startup-high','startup'),sb=await run('startup-balanced','startup');
for(const r of [candidate,high])for(const field of ['quality','viewport','dpr','browser','graphics','profile'])assert.deepEqual(r.data[field],baseline.data[field]);
for(const field of ['quality','viewport','dpr','browser','graphics','profile'])assert.deepEqual(preGuard.data[field],balanced.data[field]);
const goal=await read('.game-dev/goals/static-shadow-submissions.json');assert.equal(goal.state.status,'met');assert.equal(goal.state.iterations.length,1);assert.equal(goal.state.iterations[0].runId,candidate.id);
for(const r of [balanced,sh,sb])assert.equal(r.data.buildId,high.data.buildId);
for(const f of high.data.inputs){const b=await fs.readFile(f.path);assert.equal(b.length,f.bytes);assert.equal(createHash('sha256').update(b).digest('hex'),f.sha256);}
for(const r of [high,balanced]){assert.equal(r.data.summary.heldRenderFrames,0);assert.equal(r.data.summary.intervalsOver100ms,0);assert.equal(r.data.initial.world.architecture.staticShadows.drawsSaved,28);assert.equal(r.data.final.world.architecture.staticShadows.drawsSaved,28);}
assert(high.data.summary.maxTotalDrawCalls<=180);assert(balanced.data.summary.maxActiveTriangles<=250000);
for(const r of [sh,sb]){assert.equal(r.data.profile.revision,2);assert(r.data.firstPlayTransferredBytes<=(r.data.quality==='high'?12_000_000:8_000_000));assert(r.data.ready.observation.readyAt<=6000);assert.equal(r.data.ready.state.world.architecture.staticShadows.drawsSaved,28);}
const views=await read(`${stage}/views-final/comparison.json`);assert(views.pass&&views.rows.length===10&&views.rows.every(r=>r.identical&&r.beforeDraws-r.afterDraws===28));
const browsers=await read(`${stage}/browser.json`);assert(browsers.pass&&browsers.rows.length===3);assert((await read(`${stage}/no-uint.json`)).pass);
assert((await read(`${stage}/journey/report.json`)).pass);assert((await read(`${stage}/context/report.json`)).pass);
const unit=await fs.readFile(`${stage}/unit.log`,'utf8');assert(unit.includes('pass 76')&&unit.includes('fail 0'));
const rebuilt=await read(`${stage}/evaluated-rebuild.json`);assert(rebuilt.pass&&rebuilt.evaluatedBuildId===candidate.data.buildId&&rebuilt.filesCompared===candidate.data.inputs.length);
async function files(dir){const out=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())out.push(...await files(p));else if(e.isFile())out.push(p);}return out;}
assert.deepEqual((await files('dist')).sort(),high.data.inputs.map(r=>r.path).sort());const bundleBytes=high.data.inputs.reduce((n,r)=>n+r.bytes,0);assert(bundleBytes<=120_000_000);
await fs.writeFile(`${stage}/bundle-inventory.json`,JSON.stringify({buildId:high.data.buildId,files:high.data.inputs.length,bytes:bundleBytes,rawBudgetBytes:120_000_000,withinBudget:true,entries:high.data.inputs},null,2));
const result={date:new Date().toISOString(),pass:true,buildId:high.data.buildId,goalStatus:goal.state.status,goal:{baseline:baseline.id,baselineDraws:baseline.data.summary.maxTotalDrawCalls,evaluatedCandidate:candidate.id,evaluatedBuild:candidate.data.buildId,candidateDraws:candidate.data.summary.maxTotalDrawCalls,iterations:1},qualification:[high,balanced].map(r=>({quality:r.data.quality,runId:r.id,...r.data.summary,additionalGeometryBufferBytes:r.data.initial.world.architecture.staticShadows.additionalBufferBytes})),startup:[sh,sb].map(r=>({quality:r.data.quality,runId:r.id,bytes:r.data.firstPlayTransferredBytes,readyMs:r.data.ready.observation.readyAt,profileRevision:r.data.profile.revision})),checks:{unit:76,journey:37,contextRestore:true,normalEngines:3,noUintCapabilityFixture:true,pixelIdenticalViews:10},views:views.rows,runs:[baseline,candidate,preGuard,high,balanced,sh,sb].map(({data,...r})=>r),postGoalRepair:'32-bit index capability guard added after the one evaluated candidate. Unsupported devices retain original draws. Final supported build separately qualified; the bounded goal was not reopened.',fullReleaseAccepted:false,limits:['Final captures are one traversal per tier, not the required final repeat study or audio-enabled soak.','Wide arrival remains 233 High / 109 Balanced total draws; the full scene draw budget is still open even though the High traversal goal passed.','Desktop synthetic startup and capability fixtures do not prove physical-device or hosted performance.','Additional buffer bytes are explicit position/normal/index payload, excluding driver/CPU/padding; texture inventory is not total native VRAM.','Full human/device claims remain unverified; the plan permits recording unavailable-device limits and does not make the recommended pilot an unconditional publication blocker.']};
Object.assign(result,{evaluatedSourceRebuild:rebuilt,bundle:{files:high.data.inputs.length,bytes:bundleBytes,within120MBBudget:true}});
await fs.writeFile(`${stage}/assessment.json`,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({pass:true,buildId:result.buildId,qualification:result.qualification,startup:result.startup,bundle:result.bundle}));
