import {chromium,firefox,webkit} from 'playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const out=process.env.EVIDENCE_DIR??'../evidence/production/audio-v1/browser';await fs.mkdir(out,{recursive:true});const report={pass:false,engines:[]};
for(const [name,type] of [['chrome',chromium],['firefox',firefox],['webkit',webkit]]){
 if(process.env.ENGINE&&process.env.ENGINE!==name)continue;
 const browser=await type.launch(name==='chrome'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}:{headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}}),row={name,checks:[],errors:[],requests:[]};report.engines.push(row);
 page.on('pageerror',e=>row.errors.push(e.message));page.on('request',r=>{if(r.url().includes('/assets/audio/'))row.requests.push(r.url());});const state=()=>page.evaluate(()=>window.__insideCodex.state().sound);const settings=async()=>{await page.getByRole('button',{name:'Settings',exact:true}).click();};const close=async()=>{await page.getByRole('button',{name:'Close dialog'}).click();};
 try{
  await page.goto('http://127.0.0.1:43211/?audioAudit');await page.getByRole('button',{name:'Step inside'}).click();assert.equal((await state()).context,'locked');assert.equal(row.requests.length,0);row.checks.push('Default muted journey creates no audio context and requests no sound assets');
  await settings();await page.locator('#sound-toggle').check();await page.waitForFunction(()=>window.__insideCodex.state().sound.loops.length===2);await page.waitForFunction(()=>window.__insideCodex.state().sound.outputRms>0.0001);row.checks.push('A user gesture starts decoded music and ambience with measurable output');
  // Keyboard events operate the sliders; no gameplay state mutation is used.
  await page.locator('#audio-voice').focus();await page.keyboard.press('Home');await page.locator('#audio-music').focus();await page.keyboard.press('End');await page.locator('#audio-ambience').focus();await page.keyboard.press('Home');
  let s=await state();assert.equal(s.levels.voice,0);assert.equal(s.levels.music,1);assert.equal(s.levels.ambience,0);assert.equal(s.levels.effects,.55);await page.waitForFunction(()=>window.__insideCodex.state().sound.gains.ambience<.001);row.checks.push('Keyboard-operated independent sliders isolate channels and preserve effects');
  await close();await page.getByRole('button',{name:'Pause',exact:true}).click();await page.waitForFunction(()=>window.__insideCodex.state().sound.context==='suspended');assert((await state()).paused);await page.getByRole('button',{name:'Resume',exact:true}).click();await page.waitForFunction(()=>window.__insideCodex.state().sound.context==='running');await page.keyboard.press('Escape');await page.waitForFunction(()=>window.__insideCodex.state().sound.context==='suspended');await page.keyboard.press('Escape');row.checks.push('Pause button and Escape both suspend audio and resume the transport');
  await settings();await page.locator('#audio-ambience').focus();await page.keyboard.press('End');await close();
  for(const mission of [9,5,12,1,9]){await page.getByRole('button',{name:new RegExp(`^Mission ${mission}:`)}).click();}
  await page.waitForFunction(()=>{const s=window.__insideCodex.state().sound;return s.loops.includes('wing-2')&&s.retiring===0&&s.pending.length===0;});s=await state();assert.equal(s.loops.length,2);assert.equal(s.wing,2);row.checks.push('Rapid wing changes discard stale downloads and leave one score and one ambient loop');
  await settings();await page.locator('#sound-toggle').uncheck();await page.waitForFunction(()=>window.__insideCodex.state().sound.context==='suspended');assert.equal((await state()).caption,'');await page.screenshot({path:`${out}/${name}-settings.png`});row.checks.push('Master mute suspends every bus and clears narration');
  await page.reload();await page.waitForFunction(()=>window.__insideCodex?.state().ready);s=await state();assert.equal(s.context,'locked');assert.equal(s.levels.music,1);assert.equal(s.levels.voice,0);assert(s.muted);row.checks.push('Reload retains channel levels and mute without auto-starting sound');
  await settings();let fail=true;await page.route('**/assets/audio/wing-0.mp3',async route=>fail?route.abort():route.continue());await page.locator('#sound-toggle').check();await page.waitForFunction(()=>window.__insideCodex.state().sound.failures.includes('wing-0'));assert(await page.locator('#sound-status').textContent());fail=false;await page.getByRole('button',{name:'Retry sound',exact:true}).click();await page.waitForFunction(()=>window.__insideCodex.state().sound.loops.includes('wing-0'));assert.equal((await state()).failures.length,0);row.checks.push('Failed sound download leaves a usable page and explicit retry restores ambience');
  for(const channel of ['music','ambience','effects']){await page.locator(`#audio-${channel}`).focus();await page.keyboard.press('Home');}await page.locator('#audio-voice').focus();await page.keyboard.press('End');await close();await page.getByRole('button',{name:'Step inside'}).click();
  await page.getByRole('button',{name:'Mission 1: The control room',exact:true}).click();await page.waitForFunction(()=>{const s=window.__insideCodex.state().sound;return s.voiceActive&&s.caption.length>0&&s.outputRms>.001;});assert.equal((await state()).voiceBackend,'recorded-kokoro-v1');
  await page.getByRole('button',{name:'Pause',exact:true}).click();await page.waitForFunction(()=>window.__insideCodex.state().sound.context==='suspended');const pausedVoice=await state();await page.waitForTimeout(350);assert.equal((await state()).time,pausedVoice.time);assert.equal((await state()).caption,pausedVoice.caption);await page.getByRole('button',{name:'Resume',exact:true}).click();await page.waitForFunction(()=>window.__insideCodex.state().sound.context==='running');await page.getByRole('button',{name:'Skip voice',exact:true}).click();assert.equal((await state()).voiceActive,false);row.checks.push('Recorded narration produces isolated voice output, freezes at pause, resumes and skips cleanly');
  let failVoice=true;await page.route('**/assets/audio/voice/*.mp3',async route=>failVoice?route.abort():route.continue());await page.getByRole('button',{name:'Mission 3: The model observatory',exact:true}).click();await page.waitForFunction(()=>window.__insideCodex.state().sound.failures.some(id=>id.startsWith('voice/')));failVoice=false;await settings();await page.getByRole('button',{name:'Retry sound',exact:true}).click();await page.waitForFunction(()=>window.__insideCodex.state().sound.voiceActive);await page.locator('#sound-toggle').uncheck();assert.equal((await state()).voiceActive,false);row.checks.push('A failed narration segment can be retried and muted without stale speech or captions');
  row.final=await state();assert.deepEqual(row.errors,[]);row.pass=true;
 }catch(error){row.error=String(error);row.state=await state().catch(()=>null);await page.screenshot({path:`${out}/${name}-failure.png`}).catch(()=>{});throw error;}
 finally{await browser.close();await fs.writeFile(`${out}/report.json`,JSON.stringify(report,null,2));}
}
report.pass=true;await fs.writeFile(`${out}/report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({pass:true,engines:report.engines.map(e=>({name:e.name,checks:e.checks}))},null,2));
