import assert from 'node:assert/strict';
export async function automationFlow(page,shot=async()=>{}){
 const state=()=>page.evaluate(()=>window.__insideCodex.state());const act=(a,v)=>page.locator(`${a==='section'?'.auto-tabs ':''}[data-action="auto-${a}"]${v===undefined?'':`[data-value="${v}"]`}`).click();
 await act('section','setup');await act('test');assert.equal((await state()).automationLab.runs.at(-1).status,'unclear');await act('config','prompt:durable');await act('test');await act('enable');assert.equal((await state()).automationLab.enabled,true);await shot('automation-tested');
 await act('section','clock');await act('advance','5m');let s=(await state()).automationLab;assert.equal(s.runs.at(-1).status,'success');assert.equal(s.runs.at(-1).notification,false);assert((await page.locator('.auto-message').textContent()).includes('Thu 2026-09-10 09:00'));await shot('automation-quiet');
 await act('source','missing');await act('advance','day');s=(await state()).automationLab;assert.equal(s.runs.at(-1).notification,true);assert.equal(s.runs.at(-1).report.finding,'missing-approval');await shot('automation-finding');
 const count=s.runs.length;await act('advance','day');await act('advance','day');assert.equal((await state()).automationLab.runs.length,count);assert((await page.locator('.auto-message').textContent()).includes('Sun 2026-09-13'));await shot('automation-weekend');await act('advance','day');assert.equal((await state()).automationLab.runs.at(-1).notification,false);
 const baseline=(await state()).automationLab.baseline;await act('source','unavailable');await act('advance','day');s=(await state()).automationLab;assert.equal(s.runs.at(-1).status,'read-failed');assert.equal(s.runs.at(-1).notification,true);assert.deepEqual(s.baseline,baseline);await shot('automation-read-failure');
 await act('source','approved');await act('advance','day');s=(await state()).automationLab;assert.equal(s.runs.at(-1).report.recovered,true);assert.equal(s.runs.at(-1).notification,true);await act('host','off');await act('advance','day');s=(await state()).automationLab;assert.equal(s.runs.at(-1).status,'host-unavailable');assert.equal(s.runs.at(-1).report,null);assert.equal(s.runs.at(-1).notification,false);await shot('automation-host-off');
 await act('host','on');assert.equal((await state()).world.automation.verified,false);await act('advance','day');assert.equal((await state()).world.automation.verified,true);await act('section','runs');await shot('automation-verified');
}
