import {chromium} from 'playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {automationFlow} from './automation-flow.mjs';
const out=process.env.EVIDENCE_DIR??'../evidence/production/automation-ui-v1',url=process.env.TEST_URL??'http://127.0.0.1:43211/';await fs.mkdir(out,{recursive:true});
const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const page=await b.newPage({deviceScaleFactor:2});const errors=[],checks=[],failed=[];page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>failed.push(r.url()));const state=()=>page.evaluate(()=>window.__insideCodex.state());const act=(a,v)=>page.locator(`${a==='section'?'.auto-tabs ':''}[data-action="auto-${a}"]${v===undefined?'':`[data-value="${v}"]`}`).click();
try{
 for(const [width,height] of [[1440,900],[390,844],[844,390]]){
  await page.setViewportSize({width,height});await page.goto(url);await page.waitForFunction(()=>window.__insideCodex?.state().ready);await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('#motion-toggle').check();await page.getByRole('button',{name:'Close dialog',exact:true}).click();await page.getByRole('button',{name:'The map',exact:true}).click();await page.locator('.map-card[data-index="10"]').click();await page.waitForFunction(()=>window.__insideCodex.state().world.transition===0);const key=`${width}x${height}`;await page.screenshot({path:`${out}/arrival-${key}.png`});
  for(const quality of ['high','balanced']){await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('#quality').selectOption(quality);await page.getByRole('button',{name:'Close dialog',exact:true}).click();for(const id of ['clock','runs','setup']){const p=(await state()).world.automation.ports.find(p=>p.id===id).screen;assert(await page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.id==='world',p),`${key} ${id} occluded`);await page.locator('#world').click({position:p});assert.equal((await state()).automationLab.section,id);}checks.push(`${key} ${quality}: all three spatial controls open their matching panel`);}
  await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('#quality').selectOption('high');await page.getByRole('button',{name:'Close dialog',exact:true}).click();
  await act('config','prompt:durable');await page.locator('#auto-timezone').selectOption('UTC');assert.equal((await state()).automationLab.config.timezone,'UTC');assert((await page.locator('.auto-clock small').textContent()).includes('2026-09-11 09:00'));await act('test');await act('enable');await page.locator('#auto-hour').selectOption('15');assert.equal((await state()).automationLab.enabled,false);assert.equal((await state()).automationLab.testedVersion,null);await act('restart');
  await automationFlow(page,async name=>page.screenshot({path:`${out}/${name}-${key}.png`}));await page.locator('[data-action="submit"]').click();assert.equal((await state()).feedback,'correct');await act('section','clock');await act('pause');const count=(await state()).automationLab.runs.length;await act('advance','day');assert.equal((await state()).automationLab.runs.length,count);await page.locator('[data-action="submit"]').click();assert.equal((await state()).feedback,'incorrect');await page.locator('[data-action="auto-enable"]').focus();await page.keyboard.press('Enter');assert.equal((await state()).world.automation.verified,true);assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));await page.locator('[data-action="submit"]').click();await page.reload();await page.waitForFunction(()=>window.__insideCodex?.state().ready);assert.equal((await state()).progress.workspace.automationRun.config.timezone,'America/Toronto');assert((await state()).progress.workspace.automationRun.runs.some(r=>r.status==='host-unavailable'));
  checks.push(`${key}: timezone preview, edit invalidation, quiet/finding/weekend runs, source failure/recovery, host failure/recovery, pause, keyboard enable and receipt reload pass`);
 }
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);await fs.writeFile(`${out}/report.json`,JSON.stringify({pass:true,checks,errors,failed},null,2));console.log(JSON.stringify({pass:true,checks},null,2));
}catch(e){await page.screenshot({path:`${out}/failure.png`});await fs.writeFile(`${out}/failure.json`,JSON.stringify({error:String(e),checks,state:await state()},null,2));throw e;}finally{await b.close();}
