import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
import {freshCapstone,capstoneEdit,capstoneAction as act,capstoneRubric,capstonePass,capstoneReceipt,restoreCapstone,computeCedar,cedarCases} from '../src/capstone-lab.mjs';import {capstoneFiles} from '../src/capstone-resources.mjs';
export function cedarReady(){let s=freshCapstone();for(const [a,v] of [['title','Cedar weekly reporting'],['summary','Deliver the requested period report and metrics, independently recompute saved claims and validate the next period.'],['period','2026-09-07'],['deliverable','report-csv'],['metric','completed'],['metric','completion'],['metric','growth'],['source','brief'],['source','current'],['source','instructions'],['data'],['files'],['scope','training']])s=act(s,a,v);return s;}
export function cedarSolved(){let s=act(cedarReady(),'procedure','previous');for(const week of ['first','next']){s=act(s,'week',week);for(const a of ['run','readback','check'])s=act(s,a);}for(const [a,v] of [['cadence','monday-9'],['timezone','America/Toronto'],['alerts','changes'],['failure','preserve'],['runtime','host-available'],['rehearse'],['submit']])s=act(s,a,v);return s;}
test('A forecast is not an observed result; independent claims catch both wrong denominators',()=>{let s=cedarReady();s=act(s,'run');s=act(s,'check');assert.equal(s.outputs.first.metrics.revenue_change,12);assert(!s.checks.first.pass);assert(s.failureSeen);s=act(s,'procedure','current');s=act(s,'run');s=act(s,'check');assert.equal(s.outputs.first.metrics.revenue_change,7.41);assert(!s.checks.first.pass);s=act(s,'procedure','previous');s=act(s,'run');s=act(s,'check');assert.equal(s.outputs.first.metrics.revenue_change,8);assert(s.checks.first.pass);assert.equal(computeCedar(cedarCases.next).revenue_change,5);});
test('Effort cannot supply data or file access; broad scope and irrelevant context are scored separately',()=>{let s=act(freshCapstone(),'effort','max');s=act(s,'run');assert.deepEqual(s.outputs,{});s=cedarReady();s=act(s,'scope','workspace');s=act(s,'source','private');s=act(s,'run');assert(s.outputs.first);assert(!capstoneRubric(s)[1].pass);assert(!capstoneRubric(s)[2].pass);s=act(s,'scope','training');s=act(s,'source','private');s=act(s,'effort','max');s=act(s,'run');assert(capstoneRubric(s)[2].pass);});
test('Every saved period must be checked and opened; new revisions invalidate earlier evidence',()=>{let s=cedarSolved();assert(capstonePass(s));s=act(s,'procedure','template');assert(!capstonePass(s));s=act(s,'procedure','previous');s=act(s,'week','first');s=act(s,'run');s=act(s,'check');assert(!capstoneRubric(s)[3].pass);s=act(s,'readback');assert(!capstoneRubric(s)[3].pass);s=act(s,'week','next');for(const a of ['run','check','readback'])s=act(s,a);assert(capstoneRubric(s)[3].pass);assert(!capstonePass(s));});
test('First submitted rubric and prior hint use survive repairs and retries',()=>{let s=act(freshCapstone(),'hint');s=act(s,'submit');assert.deepEqual(s.first.scores,[false,false,false,false,false]);assert(s.first.assisted);const first=structuredClone(s.first);for(const a of cedarSolved().actions)s=act(s,a.action,a.value);assert(capstonePass(s));assert.deepEqual(s.first,first);assert.equal(s.reviews.length,2);assert(s.reviews[1].scores.every(Boolean));});
test('Recurrence evaluates actual retained files, quiet success and failed-read preservation',()=>{const s=cedarSolved(),r=s.rehearsal;assert(r.pass);assert.deepEqual(r.runs.map(x=>x.notify),[false,true,true]);assert.deepEqual(r.runs[2].files,r.runs[1].files);assert(r.runs[1].files['cedar-weekly.md'].includes('87.50%'));let bad=act(s,'failure','replace');assert.equal(bad.rehearsal,null);bad=act(bad,'rehearse');assert(!bad.rehearsal.pass);assert.deepEqual(bad.rehearsal.runs[2].files,{});bad=act(bad,'cadence','friday-9');bad=act(bad,'rehearse');assert.equal(bad.rehearsal.runs[0].date,'2026-09-18');assert(!bad.rehearsal.pass);});
test('Saved unfinished attempts and completed receipts replay exactly; forged artifacts or scores fail',()=>{let s=act(cedarReady(),'run');assert(restoreCapstone(capstoneReceipt(s)));s=cedarSolved();const r=capstoneReceipt(s);assert(restoreCapstone(r));for(const change of [r=>r.first.scores[0]=false,r=>r.outputs.first.files['metrics.csv']='fake',r=>r.rehearsal.runs[2].files={},r=>r.hints=99]){const bad=structuredClone(r);change(bad);assert.equal(restoreCapstone(bad),null);}assert.equal(restoreCapstone({...r,actions:[...r.actions,{action:'invent-success'}]}),null);});
test('Exported Python independently checks actual files and rejects a wrong report or copied calculation on fresh input',async()=>{const files=capstoneFiles(capstoneReceipt(cedarSolved()));const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cedar-capstone-'));try{for(const [name,text] of Object.entries(files)){const p=path.join(dir,name);await fs.mkdir(path.dirname(p),{recursive:true});await fs.writeFile(p,text);}const cwd=path.join(dir,'cedar-capstone');let r=spawnSync('python3',['check_reports.py'],{cwd,encoding:'utf8'});assert.equal(r.status,0,r.stdout+r.stderr);const report=path.join(cwd,'reports/2026-09-07/cedar-weekly.md');await fs.writeFile(report,(await fs.readFile(report,'utf8')).replace('8.00%','12.00%'));r=spawnSync('python3',['check_reports.py'],{cwd,encoding:'utf8'});assert.equal(r.status,1);await fs.appendFile(path.join(cwd,'current.csv'),'2026-09-21,32,28,11901\n');r=spawnSync('python3',['build_reports.py'],{cwd,encoding:'utf8'});assert.equal(r.status,0,r.stdout+r.stderr);r=spawnSync('python3',['check_reports.py'],{cwd,encoding:'utf8'});assert.equal(r.status,0,r.stdout+r.stderr);await fs.writeFile(path.join(cwd,'procedure.json'),JSON.stringify({revenue_formula:'template'}));spawnSync('python3',['build_reports.py'],{cwd});r=spawnSync('python3',['check_reports.py'],{cwd,encoding:'utf8'});assert.equal(r.status,1);assert(r.stdout.includes('revenue_change'));}finally{await fs.rm(dir,{recursive:true,force:true});}});

test('Text input coalesces while retaining replayable progress before blur',()=>{let s=freshCapstone();for(const value of ['C','Ce','Ced','Cedar task'])s=capstoneEdit(s,'title',value);assert.equal(s.actions.length,1);assert.equal(s.revision,2);assert.equal(restoreCapstone(capstoneReceipt(s)).definition.title,'Cedar task');s=act(s,'submit');s=capstoneEdit(s,'title','Revised title');assert.equal(s.actions.length,3);assert.equal(s.first.revision,2);});
