import {chromium} from 'playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {capstoneFlow} from './capstone-flow.mjs';
const out=process.env.EVIDENCE_DIR??'../evidence/production/capstone-ui-v1',url=process.env.TEST_URL??'http://127.0.0.1:43211/';await fs.mkdir(out,{recursive:true});const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const checks=[],errors=[],failed=[];
try{for(const [width,height] of [[1440,900],[390,844],[844,390]]){const context=await b.newContext({viewport:{width,height},deviceScaleFactor:2});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>failed.push(r.url()));const state=()=>page.evaluate(()=>window.__insideCodex.state()),key=`${width}x${height}`;const act=(a,v)=>page.locator(`${a==='section'?'.cedar-tabs ':''}[data-action="cedar-${a}"]${v===undefined?'':`[data-value="${v}"]`}`).click();
 try{await page.goto(url);await page.waitForFunction(()=>window.__insideCodex?.state().ready);await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('#motion-toggle').check();await page.getByRole('button',{name:'Close dialog',exact:true}).click();await page.getByRole('button',{name:'The map',exact:true}).click();await page.locator('[data-action="capstone"]').click();await page.waitForFunction(()=>window.__insideCodex.state().world.transition===0);await page.screenshot({path:`${out}/arrival-${key}.png`});
 for(const quality of ['high','balanced']){await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('#quality').selectOption(quality);await page.getByRole('button',{name:'Close dialog',exact:true}).click();for(const id of ['sources','report','repeat']){const p=(await state()).world.capstone.ports.find(p=>p.id===id).screen;assert(await page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.id==='world',p),`${key} ${id} occluded`);await page.locator('#world').click({position:p});assert.equal((await state()).cedarLab.section,id);}checks.push(`${key} ${quality}: all three capstone spatial controls open the matching panel`);}
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('#quality').selectOption('high');await page.getByRole('button',{name:'Close dialog',exact:true}).click();await act('section','brief');await page.locator('#cedar-title').fill('Saved before blur');await page.reload();await page.waitForFunction(()=>window.__insideCodex?.state().ready);await page.getByRole('button',{name:'The map',exact:true}).click();await page.locator('[data-action="capstone"]').click();assert.equal((await state()).cedarLab.definition.title,'Saved before blur');await act('section','report');await act('run');assert.deepEqual((await state()).cedarLab.outputs,{});await page.locator('[data-action="hint"]').click();await page.locator('[data-action="submit"]').click();assert.equal((await state()).feedback,'incorrect');assert.deepEqual((await state()).cedarLab.first.scores,[false,false,false,false,false]);assert((await state()).cedarLab.first.assisted);
 await page.reload();await page.waitForFunction(()=>window.__insideCodex?.state().ready);await page.getByRole('button',{name:'The map',exact:true}).click();await page.locator('[data-action="capstone"]').click();assert((await state()).cedarLab.first.assisted);
 await capstoneFlow(page,async name=>page.screenshot({path:`${out}/${name}-${key}.png`}));assert.deepEqual((await state()).cedarLab.first.scores,[false,false,false,false,false]);assert((await state()).cedarLab.reviews.at(-1).scores.every(Boolean));assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
 await act('section','repeat');await page.locator('#cedar-failure').selectOption('replace');assert.equal((await state()).cedarLab.rehearsal,null);await page.locator('[data-action="submit"]').click();assert.equal((await state()).feedback,'incorrect');await act('rehearse');assert.equal((await state()).cedarLab.rehearsal.pass,false);await page.screenshot({path:`${out}/cedar-bad-recurrence-${key}.png`});await page.locator('#cedar-failure').selectOption('preserve');await act('rehearse');await page.locator('[data-action="submit"]').focus();await page.keyboard.press('Enter');assert.equal((await state()).feedback,'correct');
 await page.locator('[data-action="next"]').click();assert.equal((await state()).screen,'finish');await page.reload();await page.waitForFunction(()=>window.__insideCodex?.state().ready);assert((await state()).progress.workspace.capstoneReview.passed);assert.deepEqual((await state()).progress.capstone,[false,false,false,false,false]);checks.push(`${key}: blocked access, assisted first-review persistence, calculation repair, fresh-period transfer, recurrence repair, keyboard submission and saved handoff reload pass`);
 }catch(e){await page.screenshot({path:`${out}/failure-${key}.png`});await fs.writeFile(`${out}/failure-${key}.json`,JSON.stringify({error:String(e),state:await state()},null,2));throw e;}finally{await context.close();}}
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);await fs.writeFile(`${out}/report.json`,JSON.stringify({pass:true,checks,errors,failed},null,2));console.log(JSON.stringify({pass:true,checks},null,2));
}finally{await b.close();}
