import assert from 'node:assert/strict';
export async function capstoneFlow(page,shot=async()=>{}){
 const act=(a,v)=>page.locator(`${a==='section'?'.cedar-tabs ':''}[data-action="cedar-${a}"]${v===undefined?'':`[data-value="${v}"]`}`).click();const field=(id,v)=>page.locator(`[data-cedar-field="${id}"]`).selectOption(v);const state=()=>page.evaluate(()=>window.__insideCodex.state());
 await act('section','brief');await page.locator('#cedar-title').fill('Cedar weekly reporting');await page.locator('#cedar-title').press('Tab');await page.locator('#cedar-summary').fill('Deliver the requested report and metrics from current actuals, independently check the saved claims and test the following period.');await page.locator('#cedar-summary').press('Tab');await field('period','2026-09-07');await field('deliverable','report-csv');for(const id of ['completed','completion','growth'])await act('metric',id);await shot('cedar-definition');
 await act('section','sources');for(const id of ['brief','current','instructions']){await act('inspect',id);await act('source',id);}await act('data');await act('files');await field('scope','training');
 await act('section','report');await act('run');await act('readback');await act('check');assert.equal((await state()).cedarLab.outputs.first.metrics.revenue_change,12);assert.equal((await state()).cedarLab.checks.first.pass,false);await shot('cedar-mismatch');
 await page.locator('.cedar-procedure summary').click();await shot('cedar-procedure');await act('procedure','previous');await act('run');await act('readback');await act('check');assert((await state()).cedarLab.checks.first.pass);await shot('cedar-first-checked');await field('week','next');await act('run');await act('readback');await act('check');assert.equal((await state()).cedarLab.outputs.next.metrics.revenue_change,5);await shot('cedar-next-checked');
 await act('section','repeat');for(const [id,v] of [['cadence','monday-9'],['timezone','America/Toronto'],['alerts','changes'],['failure','preserve'],['runtime','host-available']])await field(id,v);await act('rehearse');assert((await state()).cedarLab.rehearsal.pass);await shot('cedar-rehearsal');
 await page.locator('[data-action="submit"]').click();assert.equal((await state()).feedback,'correct');assert((await state()).progress.workspace.capstoneReview.passed);await shot('cedar-submitted');
}
