import {chromium} from 'playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {handoffFlow} from './handoff-flow.mjs';
const out=process.env.EVIDENCE_DIR??'../evidence/production/handoff-ui-v1',url=process.env.TEST_URL??'http://127.0.0.1:43211/';await fs.mkdir(out,{recursive:true});
const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const page=await b.newPage({deviceScaleFactor:2});const errors=[],checks=[],failed=[];page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>failed.push(r.url()));const state=()=>page.evaluate(()=>window.__insideCodex.state());const act=(a,v)=>page.locator(`${a==='section'?'.handoff-tabs ':''}[data-action="handoff-${a}"]${v===undefined?'':`[data-value="${v}"]`}`).click();
try{
 for(const [width,height] of [[1440,900],[390,844],[844,390]]){
  await page.setViewportSize({width,height});await page.goto(url);await page.waitForFunction(()=>window.__insideCodex?.state().ready);await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('#motion-toggle').check();await page.getByRole('button',{name:'Close dialog',exact:true}).click();await page.getByRole('button',{name:'The map',exact:true}).click();await page.locator('.map-card[data-index="11"]').click();await page.waitForFunction(()=>window.__insideCodex.state().world.transition===0);const key=`${width}x${height}`;await page.screenshot({path:`${out}/arrival-${key}.png`});
  for(const quality of ['high','balanced']){await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('#quality').selectOption(quality);await page.getByRole('button',{name:'Close dialog',exact:true}).click();for(const id of ['prepare','evidence','delivery']){const p=(await state()).world.handoff.ports.find(p=>p.id===id).screen;assert(await page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.id==='world',p),`${key} ${id} occluded`);await page.locator('#world').click({position:p});assert.equal((await state()).handoffLab.section,id);}checks.push(`${key} ${quality}: all three spatial controls open their matching panel`);}
  await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('#quality').selectOption('high');await page.getByRole('button',{name:'Close dialog',exact:true}).click();await act('preserve');assert.equal((await state()).handoffLab.recovery,null);await act('deploy');assert.equal((await state()).handoffLab.delivered.id,1);await page.screenshot({path:`${out}/handoff-no-recovery-${key}.png`});
  await handoffFlow(page,async name=>page.screenshot({path:`${out}/${name}-${key}.png`}));await page.locator('[data-action="submit"]').click();assert.equal((await state()).feedback,'correct');
  const backup=(await state()).handoffLab.recovery;await act('section','prepare');await act('repair','hide');await act('section','delivery');await act('surface','local');await act('check');assert.equal((await state()).handoffLab.localCheck.pass,false);assert.equal((await state()).world.handoff.verified,false);await act('section','prepare');await act('repair','relative');await act('select','data');await act('pack');await act('section','delivery');await act('deploy');await act('check');assert.equal((await state()).handoffLab.deliveredCheck.pass,false);await page.screenshot({path:`${out}/handoff-missing-data-${key}.png`});
  await act('section','prepare');await act('select','data');await act('section','delivery');await act('surface','local');await act('check');await act('section','prepare');await act('pack');await act('section','delivery');await act('deploy');await page.locator('[data-action="handoff-check"]').focus();await page.keyboard.press('Enter');assert.equal((await state()).world.handoff.verified,true);assert.deepEqual((await state()).handoffLab.recovery,backup);assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));await page.locator('[data-action="submit"]').click();await page.reload();await page.waitForFunction(()=>window.__insideCodex?.state().ready);assert((await state()).progress.workspace.handoffRelease.delivered.files['index.html'].includes('src="./assets/brand.svg"'));
  checks.push(`${key}: recovery prerequisite, local/delivered divergence, restore verification, missing-file and hidden-image refusal, keyboard check and byte-preserving receipt reload pass`);
 }
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);await fs.writeFile(`${out}/report.json`,JSON.stringify({pass:true,checks,errors,failed},null,2));console.log(JSON.stringify({pass:true,checks},null,2));
}catch(e){await page.screenshot({path:`${out}/failure.png`});await fs.writeFile(`${out}/failure.json`,JSON.stringify({error:String(e),checks,state:await state()},null,2));throw e;}finally{await b.close();}
