import test from 'node:test';import assert from 'node:assert/strict';import {freshHandoff,handoffAction,handoffPass,handoffReceipt,normalizeHandoffReceipt,handoffFiles,analyzeDelivery,candidateFiles} from '../src/handoff-lab.mjs';
const go=(s,...steps)=>steps.reduce((v,[a,b])=>handoffAction(v,a,b),s);
export function solvedHandoff(){return go(freshHandoff(),['check'],['preserve'],['surface','local'],['check'],['pack'],['deploy'],['check'],['rollback'],['check'],['repair','relative'],['notes','useful'],['select','guide'],['surface','local'],['check'],['pack'],['deploy'],['check']);}
test('An absolute asset path passes at the local root and fails under the delivered mount',()=>{const files=candidateFiles(freshHandoff());const local=analyzeDelivery(files,'local'),delivered=analyzeDelivery(files,'delivered');assert(local.pass);assert(!delivered.pass);assert.equal(delivered.requests[0].url,'/assets/brand.svg');assert.equal(delivered.requests[0].status,404);assert.equal(delivered.requests[1].status,200);});
test('Preserve requires current delivered evidence and staging requires the working recovery copy',()=>{let s=go(freshHandoff(),['preserve'],['pack'],['deploy']);assert.equal(s.recovery,null);assert.equal(s.delivered.id,1);s=go(s,['surface','local'],['check'],['preserve']);assert.equal(s.recovery,null);s=go(s,['surface','delivered'],['check'],['preserve']);assert.equal(s.recovery.id,1);s=go(s,['deploy']);assert.equal(s.delivered.id,2);assert.equal(s.deliveredCheck,null);});
test('Rollback is not verified until the restored delivery passes; it preserves the earlier files',()=>{let s=go(freshHandoff(),['check'],['preserve'],['pack'],['deploy'],['check']);const backup=structuredClone(s.recovery);assert(s.failureSeen);assert.equal(s.deliveredCheck.pass,false);s=go(s,['rollback']);assert(!s.rollbackVerified);assert.equal(s.deliveredCheck,null);assert.deepEqual(s.recovery,backup);s=go(s,['check'],['preserve']);assert(s.rollbackVerified);assert.deepEqual(s.recovery,backup);assert(!handoffPass(s));});
test('Removing the image hides the symptom but fails the required brand; fixing local files does not change the staged copy',()=>{let s=go(freshHandoff(),['check'],['preserve'],['pack'],['deploy'],['check'],['repair','hide'],['surface','local'],['check']);assert(!s.localCheck.pass);assert(s.delivered.files['index.html'].includes('src="/assets/brand.svg"'));s=go(s,['repair','relative']);assert.equal(s.localCheck,null);assert.equal(s.package,null);s=go(s,['check']);assert(s.localCheck.pass);assert(!handoffPass(s));});
test('Omitted artifacts and completion-only notes do not establish a usable package; the complete repaired package does',()=>{let s=solvedHandoff();assert(handoffPass(s));s=go(s,['select','data'],['pack'],['deploy'],['check']);assert(!s.deliveredCheck.pass);assert(!handoffPass(s));s=go(s,['select','data'],['notes','claim'],['surface','local'],['check'],['pack'],['deploy'],['check']);assert(s.deliveredCheck.pass);assert(!handoffPass(s));s=go(s,['notes','useful'],['surface','local'],['check'],['pack'],['deploy'],['check']);assert(handoffPass(s));});
test('The handoff receipt replays actual staged and recovery bytes and rejects tampered checks, files or action histories',()=>{const r=handoffReceipt(solvedHandoff());assert.deepEqual(normalizeHandoffReceipt(r),r);for(const change of [r=>r.delivered.files['onboarding.csv']='wrong',r=>r.recovery.files['assets/brand.svg']='wrong',r=>r.actions.pop(),r=>r.localCheck.id=999]){const b=structuredClone(r);change(b);assert.equal(normalizeHandoffReceipt(b),null);}const files=handoffFiles(r);assert(files['handoff-dock/site/northstar/index.html'].includes('src="./assets/brand.svg"'));assert(files['handoff-dock/recovery/northstar/index.html']);assert(files['handoff-dock/RELEASE-NOTES.md'].includes('--directory recovery'));assert.equal(normalizeHandoffReceipt({version:1,simulation:true,actions:[{action:'hack'}]}),null);});
