import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
import {freshReview,reviewAction,reviewPass,reviewReceipt,normalizeReviewReceipt,reviewRun,reviewCode,reviewOutput,reviewCases,runPass} from '../src/review-lab.mjs';
import {reviewFiles} from '../src/review-resources.mjs';import {freshProgress,normalizeProgress,validateAnswer} from '../src/learning.mjs';
function repaired(){let s=freshReview();for(const [a,v] of [['run','full'],['flag','owner'],['flag','files'],['repair'],['run','full'],['inspect']])s=reviewAction(s,a,v);return s;}
test('A passing narrow check misses assigned-owner and file-access regressions',()=>{let s=freshReview();s=reviewAction(s,'run','owner');assert(runPass(s.current));assert(!reviewPass(s));s=reviewAction(s,'run','full');assert(!runPass(s.current));assert.equal(s.current.items[1].actual.approval_owner,'Nina Patel');assert.equal(s.current.items[1].expected.approval_owner,'Omar Chen');assert.equal(s.current.items[0].actual.files,'');assert(s.current.items[0].checks.find(x=>x.field==='title').pass);});
test('Review feedback changes no files until an explicit repair; partial and overbroad repairs fail',()=>{let s=reviewAction(freshReview(),'run','full');s=reviewAction(s,'flag','owner');assert.equal(s.patch.owner,false);s=reviewAction(s,'repair');assert.equal(s.patch.owner,true);assert.equal(s.current,null);s=reviewAction(s,'run','full');assert(!runPass(s.current));assert.equal(s.current.items[1].actual.approval_owner,'Omar Chen');s=reviewAction(s,'flag','files');s=reviewAction(s,'flag','title');s=reviewAction(s,'repair');s=reviewAction(s,'run','full');assert(!runPass(s.current));assert(s.current.items.every(c=>c.checks.find(x=>x.field==='files').pass));assert(s.current.items.every(c=>!c.checks.find(x=>x.field==='title').pass));s=reviewAction(s,'restore','title');assert.equal(s.current,null);s=reviewAction(s,'run','full');assert(runPass(s.current));assert(!reviewPass(s));s=reviewAction(s,'inspect');assert(reviewPass(s));});
test('Completion requires reproduced failure, a current full check, and final diff inspection',()=>{let s=repaired();assert(reviewPass(s));assert(validateAnswer({kind:'review'},s));assert(!reviewPass({...s,runs:s.runs.filter(runPass)}));assert(!reviewPass({...s,inspected:0}));s=reviewAction(s,'restore','files');assert(!reviewPass(s));s=reviewAction(s,'run','owner');assert(runPass(s.current));assert(!reviewPass(s));const input=structuredClone(reviewCases[2].input);reviewOutput(repaired().patch,input);assert.deepEqual(input,reviewCases[2].input);});
test('Receipt import reconstructs code and checks and rejects tampered output or stale review',()=>{const r=reviewReceipt(repaired());assert.deepEqual(normalizeReviewReceipt(r),r);const p=freshProgress();p.workspace.reviewRepair=r;assert.deepEqual(normalizeProgress(p).workspace.reviewRepair,r);for(const mutate of [x=>x.code+='// altered',x=>x.inspected=0,x=>x.runs[0].items[0].actual.files='requested',x=>x.runs[0].revision=-1,x=>x.currentId=999,x=>x.requests[0].text='Fake review',x=>x.patch.extra=true]){const bad=structuredClone(r);mutate(bad);assert.equal(normalizeReviewReceipt(bad),null);}assert.equal(normalizeReviewReceipt(null),null);});
test('Exported code independently reproduces the regression and passes only the correct repair',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'codex-review-'));try{const r=reviewReceipt(repaired()),files=reviewFiles(r);for(const [name,content] of Object.entries(files))await fs.writeFile(path.join(dir,path.basename(name)),content);const run=name=>spawnSync(process.execPath,['check.mjs',name],{cwd:dir,encoding:'utf8'});assert.equal(run('base.mjs').status,1);const bad=run('proposed.mjs');assert.equal(bad.status,1);assert(bad.stderr.includes('Omar Chen'));const good=run('delivery.mjs');assert.equal(good.status,0,good.stderr);assert.equal(good.stdout.match(/PASS case/g).length,3);for(const patch of [{owner:true,files:false,title:false},{owner:true,files:true,title:true}]){await fs.writeFile(path.join(dir,'partial.mjs'),reviewCode(patch));assert.equal(run('partial.mjs').status,1);}const mod=await import(path.join(dir,'delivery.mjs'));for(const c of reviewCases)assert.deepEqual(mod.prepareDelivery(c.input),reviewOutput(r.patch,c.input));}finally{await fs.rm(dir,{recursive:true,force:true});}});
