import {chromium} from 'playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {steeringFlow} from './steering-flow.mjs';
const out=process.env.EVIDENCE_DIR??'../evidence/production/steering-ui-v1',url=process.env.TEST_URL??'http://127.0.0.1:43211/';await fs.mkdir(out,{recursive:true});
const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const page=await b.newPage({deviceScaleFactor:Number(process.env.TEST_DPR??2)});const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));const state=()=>page.evaluate(()=>window.__insideCodex.state());const act=(a,v)=>page.locator(`[data-action="steering-${a}"]${v===undefined?'':`[data-value="${v}"]`}`).click();
try{
 for(const [width,height] of [[1440,900],[390,844],[844,390]]){
  await page.setViewportSize({width,height});await page.goto(url);await page.waitForFunction(()=>window.__insideCodex?.state().ready);await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('#motion-toggle').check();await page.getByRole('button',{name:'Close dialog',exact:true}).click();await page.getByRole('button',{name:'The map',exact:true}).click();await page.locator('.map-card[data-index="6"]').click();await page.waitForFunction(()=>window.__insideCodex.state().world.transition===0);const key=`${width}x${height}`;await page.screenshot({path:`${out}/arrival-${key}.png`});
  for(const quality of ['high','balanced']){
   await act('restart');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('#quality').selectOption(quality);await page.getByRole('button',{name:'Close dialog',exact:true}).click();
   for(const id of ['send-steer','advance','send-queue']){const p=(await state()).world.steering.ports.find(p=>p.id===id).screen;assert(await page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.id==='world',p),`${key} ${id} occluded`);await page.locator('#world').click({position:p});if(id==='send-steer')assert.equal((await state()).steeringLab.pending.length,1);if(id==='advance')assert.equal((await state()).steeringLab.language,'fr');if(id==='send-queue')assert.equal((await state()).world.steering.queueCount,1);}
   checks.push(`${key} ${quality}: spatial steering, work-step and queue controls share the active rehearsal`);
  }
  await act('restart');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('#quality').selectOption('high');await page.getByRole('button',{name:'Close dialog',exact:true}).click();
  await act('section','messages');await act('select','email');await act('send-queue','email');await act('select','french');await act('send-queue','french');let q=(await state()).steeringLab.queue;await act('up',String(q[1].id));q=(await state()).steeringLab.queue;assert.equal(q[0].kind,'french');await act('send-now',String(q[0].id));await act('remove',String(q[1].id));await act('advance');assert.equal((await state()).steeringLab.steered,true);assert.equal((await state()).steeringLab.queue.length,0);await act('restart');
  await steeringFlow(page,async name=>page.screenshot({path:`${out}/${name}-${key}.png`}));await page.locator('[data-action="submit"]').click();assert.equal((await state()).feedback,'correct');
  // A later revision leaves an earlier email stale, then a new queued run refreshes it.
  await act('section','messages');await act('select','french');await act('send-queue','french');await act('advance');assert.equal((await state()).world.steering.carriageTargetX,0);await act('advance');assert.equal((await state()).world.steering.carriageTargetX,.74);await act('advance');assert.equal((await state()).steeringLab.checklist.version,2);assert.equal((await state()).steeringLab.draft.sourceVersion,1);assert.equal((await state()).world.steering.verified,false);await page.locator('[data-action="submit"]').click();assert.equal((await state()).feedback,'incorrect');await page.screenshot({path:`${out}/steering-stale-${key}.png`});
  await act('section','messages');await act('select','email');await act('send-queue','email');await act('send-now',String((await state()).steeringLab.queue[0].id));assert.equal((await state()).steeringLab.active.kind,'email');for(let i=0;i<2;i++){await page.locator('[data-action="steering-advance"]').focus();await page.keyboard.press('Enter');}assert.equal((await state()).world.steering.verified,true);assert.equal((await state()).steeringLab.draft.sourceVersion,2);assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));await page.locator('[data-action="submit"]').click();assert.equal((await state()).feedback,'correct');await page.reload();await page.waitForFunction(()=>window.__insideCodex?.state().ready);assert.equal((await state()).progress.workspace.steeringRun.draft.sourceVersion,2);
  checks.push(`${key}: status preserves work; steering and queued runs produce checked French artifacts; queue editing/promotion, stale-source recovery, idle Send now, keyboard advancement and replayed receipt reload pass`);
 }
 assert.deepEqual(errors,[]);await fs.writeFile(`${out}/report.json`,JSON.stringify({pass:true,checks,errors},null,2));console.log(JSON.stringify({pass:true,checks},null,2));
}catch(e){await page.screenshot({path:`${out}/failure.png`});await fs.writeFile(`${out}/failure.json`,JSON.stringify({error:String(e),checks,state:await state()},null,2));throw e;}finally{await b.close();}
