import test from 'node:test';import assert from 'node:assert/strict';
import {freshSteering,steeringAction,steeringChecks,steeringPass,steeringReceipt,normalizeSteeringReceipt,steeringFiles,checklistText} from '../src/steering-lab.mjs';
import {normalizeProgress,freshProgress,validateAnswer} from '../src/learning.mjs';
const step=(s,n=1)=>{for(let i=0;i<n;i++)s=steeringAction(s,'advance');return s;};
function complete(){let s=freshSteering();s=steeringAction(s,'send-steer','status');s=step(s);s=steeringAction(s,'send-steer','french');s=steeringAction(s,'send-queue','email');return step(s,5);}
test('Steering waits for the next boundary, status preserves the job and queued work waits for completion',()=>{let s=freshSteering();s=steeringAction(s,'send-steer','status');assert.equal(s.statusAsked,false);s=step(s);assert(s.statusAsked);assert(s.statusReport.includes('current run remains active'));assert.equal(s.active.kind,'checklist');s=steeringAction(s,'send-steer','french');s=steeringAction(s,'send-queue','email');assert.equal(s.language,'en');assert.equal(s.queue.length,1);s=step(s);assert.equal(s.checklist.language,'fr');assert.equal(s.checklist.checked,false);assert.equal(s.draft,null);s=step(s);assert(s.checklist.checked);assert.equal(s.active,null);assert.equal(s.queue.length,1);s=step(s);assert.equal(s.active.kind,'email');assert.equal(s.active.run,2);assert.equal(s.draft,null);s=step(s,2);assert(steeringPass(s));assert(validateAnswer({kind:'steering'},s));});
test('A correction after the draft was written rewrites it before checking; an email steer never cancels the checklist',()=>{let s=step(freshSteering(),2);assert.equal(s.checklist.language,'en');s=steeringAction(s,'send-steer','french');s=step(s);assert.equal(s.checklist.language,'fr');assert.equal(s.checklist.version,2);assert(!s.checklist.checked);assert.equal(s.active.step,2);let t=steeringAction(freshSteering(),'send-steer','email');t=step(t);assert.equal(t.active.kind,'checklist');assert.equal(t.queue.length,0);assert(t.events.some(e=>e.includes('queue the email')));});
test('Queued corrections can be reordered, removed or promoted; late changes cannot rewrite an earlier email',()=>{let s=freshSteering();s=steeringAction(s,'send-queue','email');s=steeringAction(s,'send-queue','french');s=steeringAction(s,'up','2');assert.equal(s.queue[0].kind,'french');s=steeringAction(s,'send-now','2');assert.equal(s.queue[0].kind,'email');assert.equal(s.pending[0].kind,'french');s=step(s);assert(s.steered);s=steeringAction(s,'remove','1');assert.equal(s.queue.length,0);s=complete();const old=s.draft.text;s=steeringAction(s,'send-queue','french');s=step(s,3);assert.equal(s.checklist.version,2);assert.equal(s.draft.sourceVersion,1);assert.equal(s.draft.text,old);assert(!steeringPass(s));s=steeringAction(s,'send-queue','email');s=step(s,3);assert(steeringPass(s));assert.equal(s.draft.sourceVersion,2);});
test('Missing a steering window remains a follow-up and can be rehearsed again',()=>{let s=step(freshSteering(),3);s=steeringAction(s,'send-steer','french');assert.equal(s.pending.length,0);assert.equal(s.queue[0].kind,'french');s=step(s,3);assert.equal(s.checklist.language,'fr');assert.equal(s.steered,false);assert(!steeringPass(s));assert.deepEqual(steeringAction(s,'restart'),freshSteering());});
test('Replayed receipts validate the action sequence, saved revisions and exact unsent outputs',()=>{const s=complete(),r=steeringReceipt(s);assert.deepEqual(normalizeSteeringReceipt(r),r);const p=freshProgress();p.workspace.steeringRun=r;assert.deepEqual(normalizeProgress(p).workspace.steeringRun,r);const files=steeringFiles(r);assert.equal(files['steering-station/checklist-fr.md'],checklistText('fr'));assert(files['steering-station/welcome-draft.txt'].includes(checklistText('fr')));for(const mutate of [x=>x.draft.status='SENT',x=>x.draft.sourceVersion=100,x=>x.checklist.text='fabricated',x=>x.actions.shift(),x=>x.events.push('fake'),x=>x.checks[0].pass=false]){const bad=structuredClone(r);mutate(bad);assert.equal(normalizeSteeringReceipt(bad),null);}assert.equal(normalizeSteeringReceipt(null),null);});
test('A full queue leaves the active task intact and its failure event remains replayable',()=>{let s=freshSteering();for(let i=0;i<7;i++)s=steeringAction(s,'send-queue','status');assert.equal(s.queue.length,6);assert.equal(s.active.kind,'checklist');for(const q of [...s.queue])s=steeringAction(s,'remove',String(q.id));s=steeringAction(s,'send-steer','status');s=step(s);s=steeringAction(s,'send-steer','french');s=steeringAction(s,'send-queue','email');s=step(s,5);assert(steeringPass(s));assert.deepEqual(normalizeSteeringReceipt(steeringReceipt(s)),steeringReceipt(s));});

test('Send now starts a selected queued follow-up when the previous run has finished',()=>{let s=complete();s=steeringAction(s,'send-queue','status');s=steeringAction(s,'send-queue','email');const id=s.queue[1].id;s=steeringAction(s,'send-now',String(id));assert.equal(s.active.kind,'email');assert.equal(s.queue.length,1);assert.equal(s.queue[0].kind,'status');s=step(s,4);assert(steeringPass(s));assert.deepEqual(normalizeSteeringReceipt(steeringReceipt(s)),steeringReceipt(s));});
