import {chromium} from 'playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {toolsFlow} from './tools-flow.mjs';
const out=process.env.EVIDENCE_DIR??'../evidence/production/tools-ui-v1',url=process.env.TEST_URL??'http://127.0.0.1:43211/';await fs.mkdir(out,{recursive:true});
const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const page=await b.newPage({deviceScaleFactor:2});const errors=[],checks=[],failed=[];page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>failed.push(r.url()));const state=()=>page.evaluate(()=>window.__insideCodex.state());const act=(a,v)=>page.locator(`${a==='section'?'.tool-tabs ':''}[data-action="tool-${a}"]${v===undefined?'':`[data-value="${v}"]`}`).click();
try{
 for(const [width,height] of [[1440,900],[390,844],[844,390]]){
  await page.setViewportSize({width,height});await page.goto(url);await page.waitForFunction(()=>window.__insideCodex?.state().ready);await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('#motion-toggle').check();await page.getByRole('button',{name:'Close dialog',exact:true}).click();await page.getByRole('button',{name:'The map',exact:true}).click();await page.locator('.map-card[data-index="8"]').click();await page.waitForFunction(()=>window.__insideCodex.state().world.transition===0);const key=`${width}x${height}`;await page.screenshot({path:`${out}/arrival-${key}.png`});
  for(const quality of ['high','balanced']){
   await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('#quality').selectOption(quality);await page.getByRole('button',{name:'Close dialog',exact:true}).click();
   for(const id of ['results','procedure','connect']){const p=(await state()).world.tools.ports.find(p=>p.id===id).screen;assert(await page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.id==='world',p),`${key} ${id} occluded`);await page.locator('#world').click({position:p});assert.equal((await state()).toolLab.section,id);}
   checks.push(`${key} ${quality}: all three spatial controls open the matching workshop panel`);
  }
  await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('#quality').selectOption('high');await page.getByRole('button',{name:'Close dialog',exact:true}).click();
  await act('inspect-package','notes');await act('install','notes');await act('connect');assert.equal((await state()).toolLab.connected,false);await act('section','results');await act('read');assert.deepEqual((await state()).toolLab.reads,{});assert((await page.locator('.tool-message').textContent()).includes('Read failed'));await page.screenshot({path:`${out}/tools-no-tool-${key}.png`});await act('restart');
  await toolsFlow(page,async name=>page.screenshot({path:`${out}/${name}-${key}.png`}));await page.locator('[data-action="submit"]').click();assert.equal((await state()).feedback,'correct');
  await act('section','connect');await act('scope','workspace');assert.equal((await state()).world.tools.verified,false);await act('connect');await page.locator('[data-action="submit"]').click();assert.equal((await state()).feedback,'incorrect');await act('scope','training');await act('connect');assert.equal((await state()).world.tools.verified,true);
  await act('disconnect');await act('section','results');await act('read');assert((await state()).toolLab.reads.northstar);assert.equal((await state()).world.tools.verified,false);await act('section','connect');await act('connect');await act('section','procedure');await act('load-skill','example');await act('load-skill','reusable');assert.equal((await state()).world.tools.verified,false);await act('section','results');
  for(const id of ['northstar','harbor']){await act('client',id);await act('run');await page.locator('[data-action="tool-verify"]').focus();await page.keyboard.press('Enter');}
  assert.equal((await state()).world.tools.verified,true);assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));await page.locator('[data-action="submit"]').click();assert.equal((await state()).feedback,'correct');await page.reload();await page.waitForFunction(()=>window.__insideCodex?.state().ready);assert((await state()).progress.workspace.toolWorkshop.outputs.harbor.csv.includes('Amir Chen'));
  checks.push(`${key}: missing connector, observed two-client defect, repaired procedure, scope/disconnection, stale-revision recovery, keyboard verification and receipt reload pass`);
 }
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);await fs.writeFile(`${out}/report.json`,JSON.stringify({pass:true,checks,errors,failed},null,2));console.log(JSON.stringify({pass:true,checks},null,2));
}catch(e){await page.screenshot({path:`${out}/failure.png`});await fs.writeFile(`${out}/failure.json`,JSON.stringify({error:String(e),checks,state:await state()},null,2));throw e;}finally{await b.close();}
