import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const out=process.env.EVIDENCE_DIR??'../evidence/walkthrough-v1/local';await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const state=()=>page.evaluate(()=>window.__insideCodex.state());
try{
 await page.goto(process.env.WALKTHROUGH_URL??'http://127.0.0.1:43211/');await page.waitForFunction(()=>window.__insideCodex?.state().ready);await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('#motion-toggle').check();await page.getByRole('button',{name:'Close dialog',exact:true}).click();await page.getByRole('button',{name:'Step inside',exact:false}).click();
 const visited=[];
 while((await state()).screen==='mission'){
  const before=await state();const kind=await page.locator('.lesson-panel').getAttribute('data-kind');await page.getByRole('button',{name:'Show answer',exact:true}).click();assert((await page.locator('.worked-answer li').count())>0);assert.deepEqual((await state()).progress.attempts,{});await page.getByRole('button',{name:'Hide answer',exact:true}).click();assert.equal(await page.locator('.worked-answer').count(),0);await page.getByRole('button',{name:'Show answer',exact:true}).click();
  if(before.mission===0&&before.stepIndex===0||kind==='models'){await page.screenshot({path:`${out}/answer-${kind}.png`});}
  visited.push({mission:before.mission,step:before.stepIndex,kind});assert(visited.length<35);await page.getByRole('button',{name:'Skip question',exact:false}).click();
 }
 assert.deepEqual((await state()).progress.completed,[]);assert(visited.length>12);
 await page.getByRole('button',{name:'Try the independent handoff',exact:false}).click();await page.getByRole('button',{name:'Show answer',exact:true}).click();assert((await state()).cedarLab.hints>0);assert.equal((await state()).cedarLab.first,null);await page.getByRole('button',{name:'Skip question',exact:false}).click();await page.getByText('You skipped the handoff.',{exact:false}).waitFor();assert.equal((await state()).cedarLab.first,null);
 const saved=(await state()).progress;await page.reload();await page.waitForFunction(()=>window.__insideCodex?.state().ready);assert.deepEqual((await state()).progress.skipped,saved.skipped);assert.deepEqual((await state()).progress.revealed,saved.revealed);
 // A later replay can still earn completion; skipping one question cannot.
 await page.getByRole('button',{name:'Step inside',exact:false}).click();await page.getByRole('button',{name:'Skip question',exact:false}).click();for(const id of ['inspect','write','check','repair'])await page.locator(`[data-action="choice"][data-value="${id}"]`).click();await page.locator('[data-action="submit"]').click();await page.locator('[data-action="next"]').click();assert(!(await state()).progress.completed.includes(0));
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Show answer',exact:true}).click();await page.screenshot({path:`${out}/portrait.png`});const box=await page.getByRole('button',{name:'Skip question',exact:false}).boundingBox();assert(box&&box.y+box.height<=844&&box.x>=0);await page.getByRole('button',{name:'Skip question',exact:false}).click();
 assert.deepEqual(errors,[]);await fs.writeFile(`${out}/report.json`,JSON.stringify({pass:true,visited,errors,checks:['reveal/hide all questions','skip every lesson','capstone assistance without submission','skip capstone without score','saved skip and reveal history','skip followed by solved question does not award mission','portrait controls']},null,2));console.log(`Passed ${visited.length} questions plus capstone, persistence and portrait checks`);
}finally{await browser.close();}
